/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY'S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS'SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY'S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __UART_SUN55IW3_H__
#define __UART_SUN55IW3_H__

/* config for DSP */
#if defined(CONFIG_ARCH_DSP) || defined(CONFIG_ARCH_RISCV)
#include <interrupt.h>

#define R_UART_NUM

/* For now, just support r_uart */
#define SUNXI_CLK_UART0		CLK_BUS_R_UART0
#define SUNXI_RST_UART0		RST_R_UART0

#define SUNXI_CLK_UART1		CLK_BUS_R_UART1
#define SUNXI_RST_UART1		RST_R_UART1

/* not support */
#define SUNXI_CLK_UART2		0
#define SUNXI_RST_UART2		0

#define SUNXI_CLK_UART3		0
#define SUNXI_RST_UART3		0

#define SUNXI_CLK_UART4		0
#define SUNXI_RST_UART4		0

#define SUNXI_CLK_UART5		0
#define SUNXI_RST_UART5		0

#ifdef CONFIG_ARCH_RISCV
#include <hal_interrupt.h>
#define SUNXI_IRQ_UART0		MAKE_IRQn(66, 0)
#define SUNXI_IRQ_UART1		MAKE_IRQn(67, 0)
/* not support */
#define SUNXI_IRQ_UART2		(0)
#define SUNXI_IRQ_UART3		(0)
#define SUNXI_IRQ_UART4		(0)
#define SUNXI_IRQ_UART5		(0)
#else
#define SUNXI_IRQ_UART0		(RINTC_IRQ_MASK | 67)
#define SUNXI_IRQ_UART1		(RINTC_IRQ_MASK | 68)
/* not support */
#define SUNXI_IRQ_UART2		(RINTC_IRQ_MASK | 0)
#define SUNXI_IRQ_UART3		(RINTC_IRQ_MASK | 0)
#define SUNXI_IRQ_UART4		(RINTC_IRQ_MASK | 0)
#define SUNXI_IRQ_UART5		(RINTC_IRQ_MASK | 0)
#endif

#define SUNXI_UART0_BASE	(0x07080000)
#define SUNXI_UART1_BASE	(0x07080400)
/* not support */
#define SUNXI_UART2_BASE	(0xffffffff)
#define SUNXI_UART3_BASE	(0xffffffff)
#define SUNXI_UART4_BASE	(0xffffffff)
#define SUNXI_UART5_BASE	(0xffffffff)

#define UART_FIFO_SIZE		(64)

#define UART0_GPIO_FUNCTION	(2)
#define UART1_GPIO_FUNCTION	(2)
/* not support */
#define UART2_GPIO_FUNCTION	(2)
#define UART3_GPIO_FUNCTION	(2)
#define UART4_GPIO_FUNCTION	(2)
#define UART5_GPIO_FUNCTION	(2)

#define UART0_TX		GPIOB(10)
#define UART0_RX		GPIOB(11)
/* not support */
#define UART1_TX		GPIOB(1)
#define UART1_RX		GPIOB(1)
#define UART2_TX		GPIOB(1)
#define UART2_RX		GPIOB(1)
#define UART3_TX		GPIOH(1)
#define UART3_RX		GPIOH(1)
#define UART4_TX		GPIOD(1)
#define UART4_RX		GPIOD(1)
#define UART5_TX		GPIOD(1)
#define UART5_RX		GPIOD(1)
#endif

#endif /*__UART_SUN55IW3_H__  */
