ccflags-y           +=  -DEPDK_DEBUG_LEVEL=EPDK_DEBUG_LEVEL_LOG_ALL                 \
                        -DUSED_BY_DESKTOP                                           \
                        $(SOLUTION_INCLUDE)

obj-y += audio_if/
obj-y += auto_off/
obj-y += charset/
obj-y += display/
obj-y += fw_update/
obj-y += keytone/
obj-y += langres/
obj-y += orchid/
obj-y += power/
obj-y += reg/
obj-y += theme/
obj-y += usb_device/
obj-y += usb_host/
obj-y += volume/
