ccflags-y           +=  -DEPDK_DEBUG_LEVEL=EPDK_DEBUG_LEVEL_LOG_ALL         \
                        -DUSED_BY_DESKTOP                                   \
                        $(SOLUTION_INCLUDE)

obj-y += activity.o
obj-y += activity_manager.o
obj-y += applet_info_manager.o
obj-y += applet_plugin_module.o
obj-y += globals.o
obj-y += mini_xml_parser.o
