subdir-ccflags-y +=	-I$(srctree)/ekernel/drivers/components/libc/dlib/sys/
subdir-ccflags-y +=	-I$(srctree)/ekernel/components/env/
subdir-ccflags-y +=	-I$(srctree)/ekernel/components/net/rt-thread/lwip/src/
subdir-ccflags-y +=	-I$(srctree)/ekernel/components/net/rt-thread/lwip/src/include/
subdir-ccflags-y +=	-I$(srctree)/ekernel/components/net/rt-thread/lwip/include/
subdir-ccflags-y +=	-I$(srctree)/ekernel/components/net/rt-thread/lwip/include/ipv4/
subdir-ccflags-y +=	-I$(srctree)/ekernel/components/net/rt-thread/lwip/src/arch/include/

obj-$(CONFIG_LWIP) += aw-ota.o
