subdir-ccflags-y +=     -I$(srctree)/ekernel/filesystem/include


obj-y += az100/
obj-y += bmp/
obj-y += charset/
obj-y += clock/
#obj-y += device_man/
obj-y += dma/
##obj-y += encrypt/
obj-y += gpio/
##obj-y += hid/
obj-y += input/
obj-y += interrupt/
obj-y += dramc/
obj-y += mod_install/
obj-y += modstub/
obj-y += mod_api/
obj-y += powerman/
obj-y += resman/
obj-y += service/
obj-y += sios/
obj-y += sys_time/
