ifeq ($(CONFIG_COMPONENTS_PM), y)
CFLAGS += -Icomponents/common/aw/pm/include/
endif

obj-y += hal_gpio.o
obj-$(CONFIG_ARCH_SUN8IW18) += sun8iw18/
obj-$(CONFIG_ARCH_SUN8IW19) += sun8iw19/
obj-$(CONFIG_ARCH_SUN8IW20) += sun8iw20/
obj-$(CONFIG_SOC_SUN20IW1) += sun8iw20/
obj-$(CONFIG_SOC_SUN20IW3) += sun8iw21/
obj-$(CONFIG_ARCH_SUN50IW11) += sun50iw11/
obj-$(CONFIG_ARCH_SUN20IW2) += sun20iw2/
obj-$(CONFIG_ARCH_SUN55IW3) += sun55iw3/
