obj-y += GUI_Timer.o
obj-$(CONFIG_GUI_KERNEL_ALLOC_EN) += GUI_Alloc.o
obj-$(CONFIG_GUI_KERNEL_KERNEL_EN) += GUI_Kernel.o
obj-$(CONFIG_GUI_KERNEL_LOCK_EN) += GUI_Lock.o
obj-$(CONFIG_GUI_KERNEL_TIME_EN) += GUI_Time.o