subdir-ccflags-y += \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/system/public/include \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/system/public/include/vo \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/system/public/include/utils \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/system/public/libion/include

obj-${CONFIG_mpp_vo} += display/
obj-y += libion/

