obj-$(CONFIG_HAL_TEST_CSI) += test_csi_offline.o test_csi_online.o

subdir-ccflags-y += -I include/hal/sdmmc/hal/
subdir-ccflags-y += -I include/hal/sdmmc/osal/
subdir-ccflags-y += -I drivers/hal/source/csi/jpeg/
subdir-ccflags-y += -I drivers/hal/include/hal/csi/
subdir-ccflags-y += -I drivers/hal/source/csi/utility/
