subdir-ccflags-y += -I$(srctree)/ekernel/drivers/include/  \
                    -I$(srctree)/include/melis/emodules/mod_orange/

obj-$(CONFIG_SUNXI_SPINOR_TEST) += test_spinor.o
obj-$(CONFIG_SUNXI_PART_TEST) += test_part.o
obj-$(CONFIG_SUNXI_IO_MULTIPLEX_TEST) += test_io_multiplex.o
obj-$(CONFIG_SUNXI_PWM_TEST) += test_pwm.o
obj-$(CONFIG_SUNXI_KEYBOARD_TEST) += test_keyboard.o
obj-$(CONFIG_SUNXI_GPIO_TEST) += test_gpio.o
obj-$(CONFIG_SUNXI_REGULATOR_TEST) += test_regulator.o
obj-$(CONFIG_SUNXI_TWI_TEST) += test_twi.o
obj-$(CONFIG_SUNXI_SPI_TEST) += test_spi.o
obj-$(CONFIG_SUNXI_RTC_TEST) += test_rtc.o
obj-$(CONFIG_SUNXI_UART_TEST) += test_uart.o
obj-$(CONFIG_SUNXI_G2D_TEST) += test_g2d_scale_job.o test_g2d_blend.o test_g2d_yu.o
obj-$(CONFIG_SUNXI_WILLOW_TEST) += test_willow.o
obj-$(CONFIG_SUNXI_CE_TEST) += test_ce.o
obj-$(CONFIG_SUNXI_CEDAR_TEST) += test_video_play.o
obj-$(CONFIG_SUNXI_CEDAR_TEST) += test_audio_play.o
obj-$(CONFIG_SUNXI_CEDAR_TEST) += test_audio_rec.o
obj-$(CONFIG_SUNXI_DISP2_TEST) += disp2/
obj-$(CONFIG_SUNXI_ORANGE_TEST) += test_orange.o
obj-$(CONFIG_SUNXI_LEDC_TEST) += test_ledc.o
obj-$(CONFIG_SUNXI_CIR_TEST) += test_cir.o
obj-$(CONFIG_SUNXI_RTP_TEST) += test_rtp.o
obj-$(CONFIG_SUNXI_STANDBY_TEST) += test_standby.o
obj-$(CONFIG_SUNXI_WDT_TEST) += test_watchdog.o
obj-$(CONFIG_SUNXI_APPLETS_TEST) += test_applets.o

obj-y += network/
