ccflags-y += 	-I$(srctree)/ekernel/subsys/avframework/v4l2/include \
		-I$(srctree)/ekernel/subsys/avframework/v4l2/include/uapi \
		-I$(srctree)/ekernel/subsys/avframework/v4l2/include/media \
		-I$(srctree)/ekernel/drivers/hal/source/ccmu \

obj-$(CONFIG_VIN_SENSOR_imx386)			+= imx386_mipi.o
obj-$(CONFIG_VIN_SENSOR_C2398)			+= C2398_mipi.o
obj-y += sensor_helper.o
