subdir-ccflags-y +=-I. -I../


lib-y += elibs_stdio.o
lib-y += elibs_stdlib.o
lib-y += elibs_string.o
lib-y += elibs_sprintf.o
lib-y += cleanflushcachebyregion.o

TARGET := $(srctree)/${elibrary-libs}/libminic.a

include $(MELIS_BASE)/scripts/Makefile.rename
