subdir-ccflags-y +=-I. -I../

lib-y += az100.o
lib-y += compress.o
lib-y += lzma/LzmaDec.o
lib-y += lzma/LzmaLib.o

TARGET := $(srctree)/${elibrary-libs}/liblzma.a

include $(MELIS_BASE)/scripts/Makefile.rename
