#### this Makefile is not be used!
#subdir-ccflags-y   +=  $(SOLUTION_INCLUDE)

#lib-y       +=  common_module.o
#lib-y       +=  magic.o

#TARGET      :=  $(MELIS_BASE)/${elibrary-libs}/libapps.a

#include     $(MELIS_BASE)/scripts/Makefile.rename
