subdir-ccflags-y += -I$(srctree)/ekernel/core/rt-thread/include

obj-${CONFIG_DRIVER_SPIBUS}         += spi/
obj-${CONFIG_DRIVER_SPINOR}         += spinor/
obj-${CONFIG_DRIVER_GPIO}           += gpio/
obj-${CONFIG_DRIVER_TIMER}          += timer/
obj-${CONFIG_DRIVER_RTC}            += rtc/
obj-y                               += net/xr829/
obj-y                               += net/brcm_wifi_libs/
obj-y                               += dma/
obj-$(CONFIG_DRIVER_WDT)            += watchdog/
obj-y                               += serial/
obj-${CONFIG_DRIVER_SOUND}          += sound/
obj-${CONFIG_DRIVER_TWIBUS}         += twi/
obj-${CONFIG_DRIVER_PWM}            += pwm/
obj-${CONFIG_DRIVER_INPUT}          += input/
obj-${CONFIG_DRIVER_G2D_RCQ}        += g2d_rcq/
obj-${CONFIG_DRIVER_DI}             += sunxi-di/
obj-${CONFIG_DRIVER_SDMMC}          += sdmmc/
obj-$(CONFIG_DISP2_SUNXI)           += disp2/
obj-$(CONFIG_DRIVER_CRYPTO_ENGINE)  += ce/
obj-${CONFIG_DRIVER_EISE}           += eise/
obj-y                               += ccmu/
obj-$(CONFIG_DRIVER_LEDC)           += ledc/
obj-$(CONFIG_DRIVER_ADC_POWER)      += adc_power/
obj-$(CONFIG_USB)           	    += usb/
obj-$(CONFIG_DRIVER_THERMAL)        += thermal/

