subdir-ccflags-y +=	-I$(srctree)/ekernel/drivers/subsys/libc/dlib/sys/
subdir-ccflags-y +=	-I$(srctree)/ekernel/subsys/env/
subdir-ccflags-y +=	-I$(srctree)/ekernel/subsys/aw/ota/
subdir-ccflags-y +=	-I$(srctree)/ekernel/subsys/net/rt-thread/lwip/src/
subdir-ccflags-y +=	-I$(srctree)/ekernel/subsys/net/rt-thread/lwip/src/include/
subdir-ccflags-y +=	-I$(srctree)/ekernel/subsys/net/rt-thread/lwip/include/
subdir-ccflags-y +=	-I$(srctree)/ekernel/subsys/net/rt-thread/lwip/include/ipv4/
subdir-ccflags-y +=	-I$(srctree)/ekernel/subsys/net/rt-thread/lwip/src/arch/include/

obj-$(CONFIG_COMPONENTS_AW_UPGRADE) += aw_upgrade.o
#obj-$(CONFIG_LWIP) += aw-ota.o
obj-y += demo/
