subdir-ccflags-y += -I$(srctree)/emodules/mod_orange/GUI/core/font/TrueType/include \
			-I$(srctree)/emodules/mod_orange/GUI/core/font/TrueType/include \
			-I$(srctree)/include/melis/module/mod_orange/gui/win 
obj-y += autofit/ base/ cache/ raster/ sfnt/ smooth/ src_plus/ truetype/ bdf/ \
		 cff/ cid/ gxvalid/ gzip/ lzw/ otvalid/ pcf/ pfr/ psaux/ pshinter/ psnames/ type1/ type42/ winfonts/