ccflags-y += -I$(srctree)/ekernel/core/rt-thread/include/libc

lib-y += CdcSysinfo.o
lib-y += CdcMessageQueue.o
lib-y += CdcIonUtil.o

TARGET := $(obj)/libcdc_base.a

include $(MELIS_BASE)/scripts/Makefile.rename

