/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY'S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS'SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY'S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __DMA_SUN55IW3_H__
#define __DMA_SUN55IW3_H__

#define SUNXI_DMAC_PBASE	(0x07121000ul)

#if defined(CONFIG_CORE_DSP0)
#define DMA_IRQ_NUM		(9)	/* DSP DMA1 channel irq non-secure to dsp */
#define NR_MAX_CHAN		16	/* total of channels */
#define START_CHAN_OFFSET      0
#endif

#define SUNXI_CLK_DMA CLK_DMA
#define SUNXI_CLK_MBUS_DMA CLK_DMA_MBUS_GATE
#define SUNXI_RST_DMA RST_BUS_DMA

/*
 * The source DRQ type and port corresponding relation
 */
#define DRQSRC_SRAM		0
#define DRQSRC_SDRAM		1
#define DRQSRC_SPDIF		2
#define DRQSRC_I2S0_RX		3
#define DRQSRC_I2S1_RX		4
#define DRQSRC_I2S2_RX		5
#define DRQSRC_I2S3_RX		6
#define DRQSRC_AUDIO_CODEC	7
#define DRQSRC_DMIC		8
#define DRQSRC_TWI0_RX		9
#define DRQSRC_TWI1_RX		10
#define DRQSRC_UART0_RX		11
#define DRQSRC_UART1_RX		12
#define DRQSRC_SPI0_RX		13
#define DRQSRC_TWI2_RX		14

/*
 * The destination DRQ type and port corresponding relation
 */
#define DRQDST_SRAM		0
#define DRQDST_SDRAM		1
#define DRQDST_SPDIF		2
#define DRQDST_I2S0_RX		3
#define DRQDST_I2S1_RX		4
#define DRQDST_I2S2_RX		5
#define DRQDST_I2S3_RX		6
#define DRQDST_AUDIO_CODEC	7
#define DRQDST_DMIC		8
#define DRQDST_TWI0_RX		9
#define DRQDST_TWI1_RX		10
#define DRQDST_UART0_RX		11
#define DRQDST_UART1_RX		12
#define DRQDST_SPI0_RX		13
#define DRQDST_TWI2_RX		14
#endif /*__DMA_SUN55IW3_H__  */
