ccflags-y           +=  -I$(MELIS_BASE)/${SOLUTION}/beetles/mod_desktop     \
                        -DEPDK_DEBUG_LEVEL=EPDK_DEBUG_LEVEL_LOG_ALL         \
                        -DUSED_BY_DESKTOP                                   \
                        $(SOLUTION_INCLUDE)

obj-y += dsk_walkman.o
obj-y += dsk_walkman_i.o
obj-y += dsk_wkm_monitor.o
obj-y += ab/
obj-y += eq/
obj-y += ff_rr_speed/
obj-y += foundation/
obj-y += fsm_ctrl/
obj-y += lyric/
obj-y += media_info/
obj-y += monitor_gate/
obj-y += npl/
obj-y += play_mode/
obj-y += play_speed/
obj-y += spectrum/
obj-y += star/
