deps_config := \
	livedesk/Kconfig \
	Kconfig.platform \
	Kconfig.melis \
	emodules/mod_charset/Kconfig \
	emodules/mod_orange/Kconfig \
	emodules/Kconfig \
	ekernel/legacy/Kconfig \
	ekernel/subsys/standby/Kconfig \
	ekernel/subsys/cplusplus/Kconfig \
	ekernel/subsys/finsh_cli/commands/iobox/Kconfig \
	ekernel/subsys/finsh_cli/commands/Kconfig \
	ekernel/subsys/finsh_cli/Kconfig \
	ekernel/subsys/avframework/eyesee-mpp/framework/sun8iw19p1/Kconfig \
	ekernel/subsys/avframework/eyesee-mpp/middleware/sun8iw19p1/Kconfig \
	ekernel/subsys/avframework/eyesee-mpp/system/public/Kconfig \
	ekernel/subsys/avframework/eyesee-mpp/Kconfig \
	ekernel/subsys/avframework/v4l2/drivers/media/sunxi_nna/Kconfig \
	ekernel/subsys/avframework/v4l2/drivers/media/platform/sunxi-eise/Kconfig \
	ekernel/subsys/avframework/v4l2/drivers/media/platform/sunxi-ise/Kconfig \
	ekernel/subsys/avframework/v4l2/drivers/media/platform/sunxi-vin/vin-cci/Kconfig \
	ekernel/subsys/avframework/v4l2/drivers/media/platform/sunxi-vin/Kconfig \
	ekernel/subsys/avframework/v4l2/drivers/media/platform/sunxi-eve/Kconfig \
	ekernel/subsys/avframework/v4l2/drivers/media/platform/Kconfig \
	ekernel/subsys/avframework/v4l2/drivers/media/v4l2-core/Kconfig \
	ekernel/subsys/avframework/v4l2/drivers/media/Kconfig \
	ekernel/subsys/avframework/Kconfig \
	ekernel/subsys/env/Kconfig \
	ekernel/subsys/aw/ota/Kconfig \
	ekernel/subsys/aw/Kconfig \
	ekernel/subsys/thirdparty/dfs/filesystems/layerfs/Kconfig \
	ekernel/subsys/thirdparty/dfs/Kconfig \
	ekernel/subsys/thirdparty/Kconfig \
	ekernel/subsys/config/devicetree/Kconfig \
	ekernel/subsys/net/rt-thread/Kconfig \
	ekernel/subsys/samples/filesystem/Kconfig \
	ekernel/subsys/samples/Kconfig \
	ekernel/subsys/Kconfig \
	ekernel/filesystem/Kconfig \
	ekernel/drivers/test/Kconfig \
	ekernel/drivers/hal/source/sunxi-di/Kconfig \
	ekernel/drivers/hal/source/mbus/Kconfig \
	ekernel/drivers/hal/source/tpadc/Kconfig \
	ekernel/drivers/hal/source/cir/Kconfig \
	ekernel/drivers/hal/source/ir/Kconfig \
	ekernel/drivers/hal/source/ledc/Kconfig \
	ekernel/drivers/hal/source/lradc/Kconfig \
	ekernel/drivers/hal/source/eise/Kconfig \
	ekernel/drivers/hal/source/ce/Kconfig \
	ekernel/drivers/hal/source/thermal/Kconfig \
	ekernel/drivers/hal/source/efuse/Kconfig \
	ekernel/drivers/hal/source/g2d_rcq/Kconfig \
	ekernel/drivers/hal/source/usb/Kconfig \
	ekernel/drivers/hal/source/gpadc/Kconfig \
	ekernel/drivers/hal/source/pwm/Kconfig \
	ekernel/drivers/hal/source/twi/Kconfig \
	drivers/hal/source/sound/component/Kconfig \
	drivers/hal/source/sound/platform/Kconfig \
	drivers/hal/source/sound/codecs/Kconfig \
	ekernel/drivers/hal/source/sound/Kconfig \
	ekernel/drivers/hal/source/dma/Kconfig \
	ekernel/drivers/hal/source/sdmmc/Kconfig \
	ekernel/drivers/hal/source/timer/Kconfig \
	ekernel/drivers/hal/source/spinor/Kconfig \
	ekernel/drivers/hal/source/gpio/Kconfig \
	ekernel/drivers/hal/source/watchdog/Kconfig \
	ekernel/drivers/hal/source/spi/Kconfig \
	ekernel/drivers/hal/source/rtc/Kconfig \
	ekernel/drivers/hal/source/regulator/Kconfig \
	ekernel/drivers/hal/source/uart/Kconfig \
	ekernel/drivers/hal/source/ccmu/Kconfig \
	ekernel/drivers/hal/source/common/Kconfig \
	ekernel/drivers/drv/source/usb/Kconfig \
	ekernel/drivers/drv/source/adc_power/Kconfig \
	ekernel/drivers/drv/source/Kconfig \
	ekernel/drivers/hal/source/disp2/soc/Kconfig \
	ekernel/drivers/hal/source/disp2/disp/Kconfig \
	ekernel/drivers/hal/source/disp2/disp/lcd/Kconfig \
	ekernel/drivers/hal/source/disp2/Kconfig \
	ekernel/drivers/drv/Kconfig \
	ekernel/core/zephyr/subsys/usb/class/Kconfig \
	ekernel/core/zephyr/subsys/usb/Kconfig \
	ekernel/core/zephyr/subsys/shell/modules/Kconfig \
	ekernel/core/zephyr/subsys/shell/Kconfig \
	ekernel/core/zephyr/subsys/net/lib/sockets/Kconfig \
	ekernel/core/zephyr/subsys/net/lib/app/Kconfig \
	ekernel/core/zephyr/subsys/net/lib/lwm2m/Kconfig.ipso \
	ekernel/core/zephyr/subsys/net/lib/lwm2m/Kconfig \
	ekernel/core/zephyr/subsys/net/lib/http/Kconfig \
	ekernel/core/zephyr/subsys/net/lib/mqtt/Kconfig \
	ekernel/core/zephyr/subsys/net/lib/dns/Kconfig \
	ekernel/core/zephyr/subsys/net/lib/zoap/Kconfig \
	ekernel/core/zephyr/subsys/net/lib/Kconfig \
	ekernel/core/zephyr/subsys/net/ip/Kconfig.stats \
	ekernel/core/zephyr/subsys/net/ip/Kconfig.rpl \
	ekernel/core/zephyr/subsys/net/ip/Kconfig.mgmt \
	ekernel/core/zephyr/subsys/net/ip/l2/ieee802154/Kconfig.radio \
	ekernel/core/zephyr/subsys/net/ip/l2/ieee802154/Kconfig \
	ekernel/core/zephyr/subsys/net/ip/l2/Kconfig \
	ekernel/core/zephyr/subsys/net/ip/Kconfig.stack \
	ekernel/core/zephyr/subsys/net/ip/Kconfig.ipv4 \
	ekernel/core/zephyr/subsys/net/ip/Kconfig.ipv6 \
	ekernel/core/zephyr/subsys/net/ip/Kconfig.debug \
	ekernel/core/zephyr/subsys/net/ip/Kconfig \
	ekernel/core/zephyr/subsys/net/Kconfig \
	ekernel/core/zephyr/subsys/logging/Kconfig \
	ekernel/core/zephyr/subsys/fs/Kconfig \
	ekernel/core/zephyr/subsys/disk/Kconfig \
	ekernel/core/zephyr/subsys/debug/Kconfig \
	ekernel/core/zephyr/subsys/cpp/Kconfig \
	ekernel/core/zephyr/subsys/console/Kconfig \
	ekernel/core/zephyr/subsys/bluetooth/shell/Kconfig \
	ekernel/core/zephyr/subsys/bluetooth/controller/Kconfig \
	ekernel/core/zephyr/subsys/bluetooth/host/mesh/Kconfig \
	ekernel/core/zephyr/subsys/bluetooth/host/Kconfig \
	ekernel/core/zephyr/subsys/bluetooth/common/Kconfig \
	ekernel/core/zephyr/subsys/bluetooth/Kconfig \
	ekernel/core/zephyr/subsys/Kconfig \
	ekernel/core/zephyr/misc/Kconfig \
	ekernel/core/zephyr/kernel/Kconfig.power_mgmt \
	ekernel/core/zephyr/kernel/Kconfig.event_logger \
	ekernel/core/zephyr/kernel/Kconfig \
	ekernel/core/zephyr/Kconfig \
	ekernel/core/rt-thread/Kconfig.scheduler \
	ekernel/core/rt-thread/Kconfig \
	ekernel/core/Kconfig \
	ekernel/arch/riscv/sbi/Kconfig \
	ekernel/arch/riscv/Kconfig \
	ekernel/arch/arm/Kconfig \
	ekernel/arch/Kconfig \
	ekernel/Kconfig \
	Kconfig

include/config/auto.conf: \
	$(deps_config)


$(deps_config): ;
