ccflags-y   +=  $(SOLUTION_INCLUDE)

lib-y       += anole/anole.o

lib-y       += rat/rat.o
lib-y       += rat/rat_miniature.o
lib-y       += rat/rat_npl.o
lib-y       += rat/rat_partition.o
lib-y       += rat/scanfile/OAL.o
lib-y       += rat/scanfile/Scan.o
lib-y       += rat/scanfile/ScanStack.o

lib-y       += robin/robin.o
lib-y       += robin/robin_i.o
lib-y       += robin/ab/robin_ab.o
lib-y       += robin/channel/robin_channel.o
lib-y       += robin/disp_output/robin_disp_output.o
lib-y       += robin/eq/robin_eq.o
lib-y       += robin/ff_rr_speed/robin_ff_rr_speed.o
lib-y       += robin/foundation/cmdQ.o
lib-y       += robin/foundation/robin_cedar_mutex.o
lib-y       += robin/foundation/robin_cmd_mutex.o
lib-y       += robin/foundation/robin_feedbackQ.o
lib-y       += robin/foundation/robin_monitor.o
lib-y       += robin/foundation/robin_syn_op.o
lib-y       += robin/fsm_ctrl/robin_fsm_ctrl.o
lib-y       += robin/lib/robin_misc.o
lib-y       += robin/lyric/robin_lyric.o
lib-y       += robin/media_info/robin_media_info.o
lib-y       += robin/npl/robin_npl.o
lib-y       += robin/palette/robin_palette.o
lib-y       += robin/play_mode/robin_play_mode.o
lib-y       += robin/play_speed/robin_play_speed.o
lib-y       += robin/spectrum/robin_spectrum.o
lib-y       += robin/star/robin_star.o
lib-y       += robin/subtitle/robin_subtitle.o
lib-y       += robin/track/robin_track.o
lib-y       += robin/video_layer/robin_video_layer.o
lib-y       += robin/video_play/robin_play_buffer.o
lib-y       += robin/video_win/robin_video_win.o
lib-y       += robin/vision_effect/robin_vision_effect.o
lib-y       += robin/volume/robin_volume.o
lib-y       += robin/zoom/robin_zoom.o

TARGET      := $(srctree)/${elibrary-libs}/libelibs_ex.a

include     $(MELIS_BASE)/scripts/Makefile.rename
