[res_10001]
name	  	=EBOOK_MENU_BOTTOM_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/menu_bottom.bmp
commentCN 	=MENU_BOTTOM
commentEN 	=MENU_BOTTOM

[res_10002]
name	  	=EBOOK_GOTO_PAGE_F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/GOTO_PAGE_F.bmp
commentCN 	=GOTO_PAGE_F
commentEN 	=GOTO_PAGE_F

[res_10003]
name	  	=EBOOK_SHOW_GOTO_PAGE_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/show_goto_page.bmp
commentCN 	=SHOW_GOTO_PAGE
commentEN 	=SHOW_GOTO_PAGE

[res_10004]
name	  	=EBOOK_AUTO_UF_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/AUTO_UF.bmp
commentCN 	=AUTO_UF
commentEN 	=AUTO_UF

[res_10005]
name	  	=EBOOK_HEAD_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/head.bmp
commentCN 	=HEAD
commentEN 	=HEAD

[res_10006]
name	  	=EBOOK_PAGE_BOTTOM11_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/page_bottom11.bmp
commentCN 	=PAGE_BOTTOM11
commentEN 	=PAGE_BOTTOM11

[res_10007]
name	  	=EBOOK_GOTO_BOTTOM_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/goto_bottom.bmp
commentCN 	=GOTO_BOTTOM
commentEN 	=GOTO_BOTTOM

[res_10008]
name	  	=EBOOK_PLAY_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/play.bmp
commentCN 	=PLAY
commentEN 	=PLAY

[res_10009]
name	  	=EBOOK_QUIT_F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/quit_f.bmp
commentCN 	=QUIT_F
commentEN 	=QUIT_F

[res_10010]
name	  	=EBOOK_DOT_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/dot.bmp
commentCN 	=DOT
commentEN 	=DOT

[res_10011]
name	  	=EBOOK_BMARK_F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/bmark_f.bmp
commentCN 	=BMARK_F
commentEN 	=BMARK_F

[res_10012]
name	  	=EBOOK_AUTO_F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/AUTO_F.bmp
commentCN 	=AUTO_F
commentEN 	=AUTO_F

[res_10013]
name	  	=EBOOK_0F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/0f.bmp
commentCN 	=0F
commentEN 	=0F

[res_10014]
name	  	=EBOOK_DEL_N_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/del_n.bmp
commentCN 	=DEL_N
commentEN 	=DEL_N

[res_10015]
name	  	=EBOOK_BODY_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/body.bmp
commentCN 	=BODY
commentEN 	=BODY

[res_10016]
name	  	=EBOOK_COUSOR_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/cousor.bmp
commentCN 	=COUSOR
commentEN 	=COUSOR

[res_10017]
name	  	=EBOOK_WKM_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/wkm.bmp
commentCN 	=WKM
commentEN 	=WKM

[res_10018]
name	  	=EBOOK_GOTO_PAGE_UF_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/GOTO_PAGE_UF.bmp
commentCN 	=GOTO_PAGE_UF
commentEN 	=GOTO_PAGE_UF

[res_10019]
name	  	=EBOOK_1_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/1.bmp
commentCN 	=1
commentEN 	=1

[res_10020]
name	  	=EBOOK_0N_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/0n.bmp
commentCN 	=0N
commentEN 	=0N

[res_10021]
name	  	=EBOOK_NAME_ROLL_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/name_roll.bmp
commentCN 	=NAME_ROLL
commentEN 	=NAME_ROLL

[res_10022]
name	  	=EBOOK_7F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/7f.bmp
commentCN 	=7F
commentEN 	=7F

[res_10023]
name	  	=EBOOK_FONTCOLOR_F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/FONTCOLOR_F.bmp
commentCN 	=FONTCOLOR_F
commentEN 	=FONTCOLOR_F

[res_10024]
name	  	=EBOOK_PAGE_BOTTOM_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/page_bottom.bmp
commentCN 	=PAGE_BOTTOM
commentEN 	=PAGE_BOTTOM

[res_10025]
name	  	=EBOOK_6F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/6f.bmp
commentCN 	=6F
commentEN 	=6F

[res_10026]
name	  	=EBOOK_5N_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/5n.bmp
commentCN 	=5N
commentEN 	=5N

[res_10027]
name	  	=EBOOK_TTS_F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/TTS_F.bmp
commentCN 	=TTS_F
commentEN 	=TTS_F

[res_10028]
name	  	=EBOOK_BMARK_UF_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/bmark_uf.bmp
commentCN 	=BMARK_UF
commentEN 	=BMARK_UF

[res_10029]
name	  	=EBOOK_2_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/2.bmp
commentCN 	=2
commentEN 	=2

[res_10030]
name	  	=EBOOK_2F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/2f.bmp
commentCN 	=2F
commentEN 	=2F

[res_10031]
name	  	=EBOOK_8N_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/8n.bmp
commentCN 	=8N
commentEN 	=8N

[res_10032]
name	  	=EBOOK_FONTCOLOR_UF_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/FONTCOLOR_UF.bmp
commentCN 	=FONTCOLOR_UF
commentEN 	=FONTCOLOR_UF

[res_10033]
name	  	=EBOOK_MUSIC_UF_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/MUSIC_UF.bmp
commentCN 	=MUSIC_UF
commentEN 	=MUSIC_UF

[res_10034]
name	  	=EBOOK_TTS_UF_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/TTS_UF.bmp
commentCN 	=TTS_UF
commentEN 	=TTS_UF

[res_10035]
name	  	=EBOOK_8F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/8f.bmp
commentCN 	=8F
commentEN 	=8F

[res_10036]
name	  	=EBOOK_2N_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/2n.bmp
commentCN 	=2N
commentEN 	=2N

[res_10037]
name	  	=EBOOK_1N_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/1n.bmp
commentCN 	=1N
commentEN 	=1N

[res_10038]
name	  	=EBOOK_PAUSE_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/pause.bmp
commentCN 	=PAUSE
commentEN 	=PAUSE

[res_10039]
name	  	=EBOOK_SELECT_OPT_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/SELECT_OPT.bmp
commentCN 	=SELECT_OPT
commentEN 	=SELECT_OPT

[res_10040]
name	  	=EBOOK_EXIT_UF_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/EXIT_UF.bmp
commentCN 	=EXIT_UF
commentEN 	=EXIT_UF

[res_10041]
name	  	=EBOOK_ENTER_F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/enter_f.bmp
commentCN 	=ENTER_F
commentEN 	=ENTER_F

[res_10042]
name	  	=EBOOK_3N_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/3n.bmp
commentCN 	=3N
commentEN 	=3N

[res_10043]
name	  	=EBOOK_4F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/4f.bmp
commentCN 	=4F
commentEN 	=4F

[res_10044]
name	  	=EBOOK_9F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/9f.bmp
commentCN 	=9F
commentEN 	=9F

[res_10045]
name	  	=EBOOK_6N_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/6n.bmp
commentCN 	=6N
commentEN 	=6N

[res_10046]
name	  	=EBOOK_EXIT_F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/EXIT_F.bmp
commentCN 	=EXIT_F
commentEN 	=EXIT_F

[res_10047]
name	  	=EBOOK_3F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/3f.bmp
commentCN 	=3F
commentEN 	=3F

[res_10048]
name	  	=EBOOK_4N_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/4n.bmp
commentCN 	=4N
commentEN 	=4N

[res_10049]
name	  	=EBOOK_ENTER_NF_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/enter_nf.bmp
commentCN 	=ENTER_NF
commentEN 	=ENTER_NF

[res_10050]
name	  	=EBOOK_1F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/1f.bmp
commentCN 	=1F
commentEN 	=1F

[res_10051]
name	  	=EBOOK_9N_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/9n.bmp
commentCN 	=9N
commentEN 	=9N

[res_10052]
name	  	=EBOOK_7N_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/7n.bmp
commentCN 	=7N
commentEN 	=7N

[res_10053]
name	  	=EBOOK_MUSIC_F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/MUSIC_F.bmp
commentCN 	=MUSIC_F
commentEN 	=MUSIC_F

[res_10054]
name	  	=EBOOK_5F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/5f.bmp
commentCN 	=5F
commentEN 	=5F

[res_10055]
name	  	=EBOOK_PAGE_BG_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/page_bg.bmp
commentCN 	=PAGE_BG
commentEN 	=PAGE_BG

[res_10056]
name	  	=EBOOK_GOTO_BG_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/goto_bg.bmp
commentCN 	=GOTO_BG
commentEN 	=GOTO_BG

[res_10057]
name	  	=EBOOK_DEL_F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/del_f.bmp
commentCN 	=DEL_F
commentEN 	=DEL_F

[res_10058]
name	  	=EBOOK_QUIT_NF_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./ebook/quit_nf.bmp
commentCN 	=QUIT_NF
commentEN 	=QUIT_NF

