/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY¡¯S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS¡¯SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY¡¯S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __MBUS_SUN20IW2_H__
#define __MBUS_SUN20IW2_H__

typedef struct {
	uint32_t MC_MCGCR;
	uint32_t MC_CPU_BWCR;
	uint32_t MC_RV_SYS_BWCR;
	uint32_t MC_MAHB_BWCR;
	uint32_t MC_DMA0_BWCR;
	uint32_t MC_DMA1_BWCR;
	uint32_t MC_CE_BWCR;
	uint32_t MC_6;
	uint32_t MC_7;
	uint32_t MC_DSP_SYS_BWCR;
	uint32_t MC_G2D_BWCR;
	uint32_t MC_DE_BWCR;
	uint32_t MC_11;
	uint32_t MC_12;
	uint32_t MC_13;
	uint32_t MC_OTHER_BWCR;
	uint32_t MC_TOTAL_BWCR;
}MBUS_PMU_REGISTER_T;

#define MBUS_CTRL_BASE  0x40102000
#define MBUS_PMU_BASE   (MBUS_CTRL_BASE + 0x009c)
#define MBUS_PMU_DBGCR  (MBUS_CTRL_BASE + 0x0008)
#define MBUS_PMU_TMR    (MBUS_CTRL_BASE + 0x000c)

#define MBUS_PMU        ((MBUS_PMU_REGISTER_T *)(MBUS_PMU_BASE))

#define AHB_MONT_BASE	0x40048400
#define AHB_MONT_CTRL	0x0000
#define AHB_MONT_PRD	0x0004
#define AHB_MONT_MST_ID 0x000C

#define AHB_MONT_RD_BW_SUM_ID0  0x0010
#define AHB_MONT_WR_BW_SUM_ID0  0x0014
#define AHB_MONT_MAX_RD_BW_ID0  0x0018
#define AHB_MONT_MAX_WR_BW_ID0  0x001C

#define AHB_MONT_RD_BW_SUM_ID1  0x0030
#define AHB_MONT_WR_BW_SUM_ID1  0x0034
#define AHB_MONT_MAX_RD_BW_ID1  0x0038
#define AHB_MONT_MAX_WR_BW_ID1  0x003C

#define AHB_MONT_RD_BW_SUM_ID2  0x0050
#define AHB_MONT_WR_BW_SUM_ID2  0x0054
#define AHB_MONT_MAX_RD_BW_ID2  0x0058
#define AHB_MONT_MAX_WR_BW_ID2  0x005C

#define AHB_MONT_RD_BW_SUM_TOTAL 0x0070
#define AHB_MONT_WR_BW_SUM_TOTAL 0x0074
#define AHB_MONT_MAX_RD_BW_TOTAL 0x0078
#define AHB_MONT_MAX_WR_BW_TOTAL 0x007C

#define CPU0_HUSTER	0x0
#define CPU1_HUSTER	0x1
#define RISCV_HUSTER	0x4
#define DSP_HUSTER	0x5
#define CE_HUSTER	0x6
#define DMA0_HUSTER	0x8
#define DMA1_HUSTER	0x9
#define CSI_HUSTER	0xA
#define ST0_HUSTER	0xC
#define ST1_HUSTER	0xD

#define MONT_PRD_NUM	0x17   //1us
#define HUSTER_ID_NUM	10   //10 ids
#endif
