subdir-ccflags-y +=     -I$(srctree)/include/melis/kernel  \
                        -I$(srctree)/include/melis/module  \
                        -I$(srctree)/include/melis/common  \
                        -I$(srctree)/include/melis/kernel/drivers \
                        -I$(srctree)/include/melis/kernel/pthread
obj-y += epos.o
obj-y += ksrv.o
obj-y += swi.o
obj-y += pthread_swi.o
