subdir-ccflags-y +=	-I$(srctree)/ekernel/drivers/indlude/drv  \
			-I$(srctree)/include/melis/ekernel/pthread \

obj-${CONFIG_DRIVERS_USB_GADGET_ADB} += adb.o
obj-${CONFIG_DRIVERS_USB_GADGET_MTP} += mtp.o
obj-y += gadget.o
obj-y += gadget_function.o
