subdir-ccflags-y += -I drivers/hal/source/usb/storage/include
subdir-ccflags-y += -I drivers/hal/source/usb/hid/Include
subdir-ccflags-y += -I drivers/hal/source/usb/uvc/Include
subdir-ccflags-y += -I drivers/hal/source/usb/carplay_host/
subdir-ccflags-y += -I drivers/hal/source/usb/host
subdir-ccflags-y += -I drivers/hal/source/usb/core

obj-y += usb_virt_bus.o		\
	usb_msg_base.o		\
	usb_msg.o		\
	usb_gen_hub_base.o	\
	usb_gen_hub.o		\
	usb_gen_hcd_rh.o	\
	usb_gen_hcd.o		\
	usb_core_interface.o	\
	usb_core_init.o		\
	usb_core_config.o	\
	usb_core_base.o		\
	usb_driver_init.o		\
	urb.o
