# Sunxi Common
obj-$(CONFIG_SND_COMMON_SUNXI_COMMON) += snd_sunxi_common.o

# Sunxi RX SYNC
obj-$(CONFIG_SND_SOC_SUNXI_RXSYNC) += snd_sunxi_rxsync.o

# Sunxi Alg Config
obj-$(CONFIG_SND_COMMON_SUNXI_ALG_CFG) += snd_sunxi_alg_cfg.o
