/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef __TV_VISIBLE_AREA_H__
#define __TV_VISIBLE_AREA_H__

#define SCREEN_SIZE_1280_720_VISIBLE_WIDTH        1208
#define SCREEN_SIZE_1280_720_VISIBLE_HEIGHT       680
#define SCREEN_SIZE_1280_720_VISIBLE_X            ( (1280-SCREEN_SIZE_1280_720_VISIBLE_WIDTH)/2 )
#define SCREEN_SIZE_1280_720_VISIBLE_Y            ( (720-SCREEN_SIZE_1280_720_VISIBLE_HEIGHT)/2 )

#define SCREEN_SIZE_1920_1080_VISIBLE_WIDTH       1812
#define SCREEN_SIZE_1920_1080_VISIBLE_HEIGHT      1020
#define SCREEN_SIZE_1920_1080_VISIBLE_X           ( (1920-SCREEN_SIZE_1920_1080_VISIBLE_WIDTH)/2 )
#define SCREEN_SIZE_1920_1080_VISIBLE_Y           ( (1080-SCREEN_SIZE_1920_1080_VISIBLE_HEIGHT)/2 )

#define SCREEN_SIZE_720_480_VISIBLE_WIDTH         660
#define SCREEN_SIZE_720_480_VISIBLE_HEIGHT        440
#define SCREEN_SIZE_720_480_VISIBLE_X             ( (720-SCREEN_SIZE_720_480_VISIBLE_WIDTH)/2 )
#define SCREEN_SIZE_720_480_VISIBLE_Y             ( (480-SCREEN_SIZE_720_480_VISIBLE_HEIGHT)/2 )

#define SCREEN_SIZE_720_576_VISIBLE_WIDTH         660
#define SCREEN_SIZE_720_576_VISIBLE_HEIGHT        536
#define SCREEN_SIZE_720_576_VISIBLE_X             ( (720-SCREEN_SIZE_720_576_VISIBLE_WIDTH)/2 )
#define SCREEN_SIZE_720_576_VISIBLE_Y             ( (576-SCREEN_SIZE_720_576_VISIBLE_HEIGHT)/2 )

enum
{
    SCREEN_TYPE_400_240,
	SCREEN_TYPE_480_640,
    SCREEN_TYPE_480_272,
    SCREEN_TYPE_720_480,
    SCREEN_TYPE_720_576,
    SCREEN_TYPE_800_480,
    SCREEN_TYPE_1024_768,
    SCREEN_TYPE_1280_720,
    SCREEN_TYPE_1920_1080,
    SCREEN_TYPE_LAST
};



#endif
