/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef __DIALOG_SCENE_H__
#define __DIALOG_SCENE_H__

#define LOW_POWER_DIALOG_TIME_ID        3000
#define POWER_OFF_DIALOG_TIME_ID        3001
#define ORCHID_UPDATE_DIALOG_TIME_ID    3002

//typedef enum
//{
//  POWEROFF_DIALOG,
//  LOWPOWER_DIALOG,
//  USBD_DIALOG,
//  ORCHID_DIALOG,
//  FW_UPDATA_DIALOG,
//  NONE_DIALOG
//}main_dialog_t;
//
//typedef struct
//{
//  /* 图层句柄 */
//  H_LYR dialog_layer;         // 弹框图层
//
//  /* 窗口句柄 */
//  H_WIN parent;
//  H_WIN dialog_win;           // 对话框窗口
//
//  /* 系统状态 dailog 相关 */
//  main_dialog_t cur_dialog;
//
//  __bool usb_connect;
//  __bool orchid_update;
//  __bool low_power;
//  __bool power_off;
//  __bool fw_update;
//
//  __bool msg_lock;
//}dialog_scene_t;

__s32 dialog_init(H_WIN hwnd);

__s32 dialog_deinit(H_WIN hwnd);

void scene_on_dialog(__gui_msg_t *msg);

#endif
