/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef __HEADBAR_COM_H__
#define __HEADBAR_COM_H__

#include <kconfig.h>

#define ID_HEADBAR_COM              0x01
#define ID_VOLUME_COM               0x02
#define ID_BRIGHT_COM               0x04
#define MAX_SIGNAL_LEVEL            6

/* 通知码 */
#define HBAR_ADJUST_VOLUME          1
#define HBAR_ADJUST_BRIGHT          2
#define HBAR_RETURN_HOME            3
#define HBAR_MUISC_STATE            4


typedef enum _headbar_cmd_id
{
    HEADBAR_CMD_SET_VOLUME          = GUI_MSG_USER_DEF,
    HEADBAR_CMD_SET_BRIGHT,
    HEADBAR_CMD_SET_FORMAT,
    HEADBAR_CMD_GET_SCN_POS,
    HEADBAR_CMD_GET_SIZE
} headbar_cmd_id;


typedef struct
{
    char        *name;
    __u16       id;

    H_WIN       parent;
    H_WIN       layer;
    RECT        rect;
    GUI_FONT    *font;           // 字体句柄
} __headbar_create_para;

H_WIN headbar_frm_create(H_WIN parent, H_LYR layer);
__s32 headbar_frm_delete(H_WIN frmwin);

__s32 headbar_enable_paint_time(__bool enable);
__s32 headbar_enable_paint_signal(__bool enable);

#endif /* __HEADBAR_COM_H__ */
