[res_2001]
name	  	=MOVIE_SSET_NEXT_UF_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_NEXT_UF.bmp
commentCN 	=SSET_NEXT_UF
commentEN 	=SSET_NEXT_UF

[res_2002]
name	  	=MOVIE_SPSC_PROG_CURSOR_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_PROG_CURSOR.bmp
commentCN 	=SPSC_PROG_CURSOR
commentEN 	=SPSC_PROG_CURSOR

[res_2003]
name	  	=MOVIE_SPSC_CHANNEL_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_CHANNEL.bmp
commentCN 	=SPSC_CHANNEL
commentEN 	=SPSC_CHANNEL

[res_2004]
name	  	=MOVIE_SSET_PAUSE_UF_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_PAUSE_UF.bmp
commentCN 	=SSET_PAUSE_UF
commentEN 	=SSET_PAUSE_UF

[res_2005]
name	  	=MOVIE_SSET_TVOUT_F_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_TVOUT_F.bmp
commentCN 	=SSET_TVOUT_F
commentEN 	=SSET_TVOUT_F

[res_2006]
name	  	=MOVIE_SSET_PREV_F_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_PREV_F.bmp
commentCN 	=SSET_PREV_F
commentEN 	=SSET_PREV_F

[res_2007]
name	  	=MOVIE_PAUSESTA_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/PAUSESTA.bmp
commentCN 	=PAUSESTA
commentEN 	=PAUSESTA

[res_2008]
name	  	=MOVIE_SPSC_ROTATE_ONE_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_ROTATE_ONE.bmp
commentCN 	=SPSC_ROTATE_ONE
commentEN 	=SPSC_ROTATE_ONE

[res_2009]
name	  	=MOVIE_SSET_A_B_F_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_A_B_F.bmp
commentCN 	=SSET_A_B_F
commentEN 	=SSET_A_B_F

[res_2010]
name	  	=MOVIE_SSET_RETURN_UF_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_RETURN_UF.bmp
commentCN 	=SSET_RETURN_UF
commentEN 	=SSET_RETURN_UF

[res_2011]
name	  	=MOVIE_SUBMENU_FCS_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/submenu_fcs.bmp
commentCN 	=SUBMENU_FCS
commentEN 	=SUBMENU_FCS

[res_2012]
name	  	=MOVIE_SSET_BG_LINE_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_BG_LINE.bmp
commentCN 	=SSET_BG_LINE
commentEN 	=SSET_BG_LINE

[res_2013]
name	  	=MOVIE_SSET_CHANNEL_UF_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_CHANNEL_UF.bmp
commentCN 	=SSET_CHANNEL_UF
commentEN 	=SSET_CHANNEL_UF

[res_2014]
name	  	=MOVIE_SSET_PLAY_MODE_F_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_PLAY_MODE_F.bmp
commentCN 	=SSET_PLAY_MODE_F
commentEN 	=SSET_PLAY_MODE_F

[res_2015]
name	  	=MOVIE_DLG_BG_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/DLG_BG.bmp
commentCN 	=DLG_BG
commentEN 	=DLG_BG

[res_2016]
name	  	=MOVIE_PROG_BG_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/PROG_BG.bmp
commentCN 	=PROG_BG
commentEN 	=PROG_BG

[res_2017]
name	  	=MOVIE_SSET_PREV_UF_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_PREV_UF.bmp
commentCN 	=SSET_PREV_UF
commentEN 	=SSET_PREV_UF

[res_2018]
name	  	=MOVIE_PROG_MID_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/PROG_MID.bmp
commentCN 	=PROG_MID
commentEN 	=PROG_MID

[res_2019]
name	  	=MOVIE_SPSC_RANDOM_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_RANDOM.bmp
commentCN 	=SPSC_RANDOM
commentEN 	=SPSC_RANDOM

[res_2020]
name	  	=MOVIE_SPSC_TVOUT_UF_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_TVOUT_UF.bmp
commentCN 	=SPSC_TVOUT_UF
commentEN 	=SPSC_TVOUT_UF

[res_2021]
name	  	=MOVIE_INFOR_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/infor.bmp
commentCN 	=INFOR
commentEN 	=INFOR

[res_2022]
name	  	=MOVIE_SSET_PLAY_F_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_PLAY_F.bmp
commentCN 	=SSET_PLAY_F
commentEN 	=SSET_PLAY_F

[res_2023]
name	  	=MOVIE_SPSC_PREV_UF_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_PREV_UF.bmp
commentCN 	=SPSC_PREV_UF
commentEN 	=SPSC_PREV_UF

[res_2024]
name	  	=MOVIE_SSETF_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSETF.bmp
commentCN 	=SSETF
commentEN 	=SSETF

[res_2025]
name	  	=MOVIE_SPSC_ONLY_ONCE_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_ONLY_ONCE.bmp
commentCN 	=SPSC_ONLY_ONCE
commentEN 	=SPSC_ONLY_ONCE

[res_2026]
name	  	=MOVIE_SPSC_PLAY_UF_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_PLAY_UF.bmp
commentCN 	=SPSC_PLAY_UF
commentEN 	=SPSC_PLAY_UF

[res_2027]
name	  	=MOVIE_SSET_CHANNEL_F_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_CHANNEL_F.bmp
commentCN 	=SSET_CHANNEL_F
commentEN 	=SSET_CHANNEL_F

[res_2028]
name	  	=MOVIE_SUBMENU_UNFCS_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/submenu_unfcs.bmp
commentCN 	=SUBMENU_UNFCS
commentEN 	=SUBMENU_UNFCS

[res_2029]
name	  	=MOVIE_PROG_CURSOR_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/PROG_CURSOR.bmp
commentCN 	=PROG_CURSOR
commentEN 	=PROG_CURSOR

[res_2030]
name	  	=MOVIE_DLG_BTN_F_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/DLG_BTN_F.bmp
commentCN 	=DLG_BTN_F
commentEN 	=DLG_BTN_F

[res_2031]
name	  	=MOVIE_SPSC_4R3_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_4R3.bmp
commentCN 	=SPSC_4R3
commentEN 	=SPSC_4R3

[res_2032]
name	  	=MOVIE_SPSC_PROG_MID_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_PROG_MID.bmp
commentCN 	=SPSC_PROG_MID
commentEN 	=SPSC_PROG_MID

[res_2033]
name	  	=MOVIE_SSET_RETURN_F_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_RETURN_F.bmp
commentCN 	=SSET_RETURN_F
commentEN 	=SSET_RETURN_F

[res_2034]
name	  	=MOVIE_SPSC_TVOUT_F_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_TVOUT_F.bmp
commentCN 	=SPSC_TVOUT_F
commentEN 	=SPSC_TVOUT_F

[res_2035]
name	  	=MOVIE_SPSC_BG_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_BG.bmp
commentCN 	=SPSC_BG
commentEN 	=SPSC_BG

[res_2036]
name	  	=MOVIE_SPSC_PROG_LEFT_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_PROG_LEFT.bmp
commentCN 	=SPSC_PROG_LEFT
commentEN 	=SPSC_PROG_LEFT

[res_2037]
name	  	=MOVIE_SPSC_16R9_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_16R9.bmp
commentCN 	=SPSC_16R9
commentEN 	=SPSC_16R9

[res_2038]
name	  	=MOVIE_PROG_LEFT_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/PROG_LEFT.bmp
commentCN 	=PROG_LEFT
commentEN 	=PROG_LEFT

[res_2039]
name	  	=MOVIE_PAL_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/PAL.BMP
commentCN 	=PAL
commentEN 	=PAL

[res_2040]
name	  	=MOVIE_SPSC_VIDEO_RATIO_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_VIDEO_RATIO.bmp
commentCN 	=SPSC_VIDEO_RATIO
commentEN 	=SPSC_VIDEO_RATIO

[res_2041]
name	  	=MOVIE_SPSC_SUBTITLE_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_SUBTITLE.bmp
commentCN 	=SPSC_SUBTITLE
commentEN 	=SPSC_SUBTITLE

[res_2042]
name	  	=MOVIE_SSET_TRACK_F_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_TRACK_F.bmp
commentCN 	=SSET_TRACK_F
commentEN 	=SSET_TRACK_F

[res_2043]
name	  	=MOVIE_SPSC_PREV_F_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_PREV_F.bmp
commentCN 	=SPSC_PREV_F
commentEN 	=SPSC_PREV_F

[res_2044]
name	  	=MOVIE_SSET_PSUSE_F_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_PSUSE_F.bmp
commentCN 	=SSET_PSUSE_F
commentEN 	=SSET_PSUSE_F

[res_2045]
name	  	=MOVIE_SSET_PLAY_MODE_UF_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_PLAY_MODE_UF.bmp
commentCN 	=SSET_PLAY_MODE_UF
commentEN 	=SSET_PLAY_MODE_UF

[res_2046]
name	  	=MOVIE_INFOR_FCS_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/infor_fcs.bmp
commentCN 	=INFOR_FCS
commentEN 	=INFOR_FCS

[res_2047]
name	  	=MOVIE_SSET_PAUSE_F_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_PAUSE_F.bmp
commentCN 	=SSET_PAUSE_F
commentEN 	=SSET_PAUSE_F

[res_2048]
name	  	=MOVIE_SPSC_PAUSE_UF_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_PAUSE_UF.bmp
commentCN 	=SPSC_PAUSE_UF
commentEN 	=SPSC_PAUSE_UF

[res_2049]
name	  	=MOVIE_SSET_SUBTITLE_F_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_SUBTITLE_F.bmp
commentCN 	=SSET_SUBTITLE_F
commentEN 	=SSET_SUBTITLE_F

[res_2050]
name	  	=MOVIE_SSET_TVOUT_UF_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_TVOUT_UF.bmp
commentCN 	=SSET_TVOUT_UF
commentEN 	=SSET_TVOUT_UF

[res_2051]
name	  	=MOVIE_SPSC_ROTATE_ALL_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_ROTATE_ALL.bmp
commentCN 	=SPSC_ROTATE_ALL
commentEN 	=SPSC_ROTATE_ALL

[res_2052]
name	  	=MOVIE_SPSC_SEQUENCE_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_SEQUENCE.bmp
commentCN 	=SPSC_SEQUENCE
commentEN 	=SPSC_SEQUENCE

[res_2053]
name	  	=MOVIE_SSET_SCREENSET_F_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_SCREENSET_F.bmp
commentCN 	=SSET_SCREENSET_F
commentEN 	=SSET_SCREENSET_F

[res_2054]
name	  	=MOVIE_SSET_NEXT_F_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_NEXT_F.bmp
commentCN 	=SSET_NEXT_F
commentEN 	=SSET_NEXT_F

[res_2055]
name	  	=MOVIE_SPSC_SCREEN_RATIO_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_SCREEN_RATIO.bmp
commentCN 	=SPSC_SCREEN_RATIO
commentEN 	=SPSC_SCREEN_RATIO

[res_2056]
name	  	=MOVIE_SSET_A_B_UF_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_A_B_UF.bmp
commentCN 	=SSET_A_B_UF
commentEN 	=SSET_A_B_UF

[res_2057]
name	  	=MOVIE_PLAYSTA_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/PLAYSTA.bmp
commentCN 	=PLAYSTA
commentEN 	=PLAYSTA

[res_2058]
name	  	=MOVIE_WKM_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/wkm.bmp
commentCN 	=WKM
commentEN 	=WKM

[res_2059]
name	  	=MOVIE_FFRR_BG_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/ffrr_BG.bmp
commentCN 	=FFRR_BG
commentEN 	=FFRR_BG

[res_2060]
name	  	=MOVIE_SSET_TRACK_UF_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_TRACK_UF.bmp
commentCN 	=SSET_TRACK_UF
commentEN 	=SSET_TRACK_UF

[res_2061]
name	  	=MOVIE_DLG_BTN_UF_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/DLG_BTN_UF.bmp
commentCN 	=DLG_BTN_UF
commentEN 	=DLG_BTN_UF

[res_2062]
name	  	=MOVIE_SSET_PLAY_UF_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_PLAY_UF.bmp
commentCN 	=SSET_PLAY_UF
commentEN 	=SSET_PLAY_UF

[res_2063]
name	  	=MOVIE_SSET_CURSOR_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_CURSOR.bmp
commentCN 	=SSET_CURSOR
commentEN 	=SSET_CURSOR

[res_2064]
name	  	=MOVIE_SPSC_PROG_BG_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_PROG_BG.bmp
commentCN 	=SPSC_PROG_BG
commentEN 	=SPSC_PROG_BG

[res_2065]
name	  	=MOVIE_SPSC_NEXT_F_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_NEXT_F.bmp
commentCN 	=SPSC_NEXT_F
commentEN 	=SPSC_NEXT_F

[res_2066]
name	  	=MOVIE_SSET_SCREENSET_UF_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_SCREENSET_UF.bmp
commentCN 	=SSET_SCREENSET_UF
commentEN 	=SSET_SCREENSET_UF

[res_2067]
name	  	=MOVIE_SPSC_ORIGIN_SIZE_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_ORIGIN_SIZE.bmp
commentCN 	=SPSC_ORIGIN_SIZE
commentEN 	=SPSC_ORIGIN_SIZE

[res_2068]
name	  	=MOVIE_SSET_SUBTITLE_UF_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SSET_SUBTITLE_UF.bmp
commentCN 	=SSET_SUBTITLE_UF
commentEN 	=SSET_SUBTITLE_UF

[res_2069]
name	  	=MOVIE_SPSC_NEXT_UF_BMP
file	  	=/home/yuzuki/WorkSpace/d1s-melis/livedesk/beetles/sun20iw1_app/res/theme/./movie/SPSC_NEXT_UF.bmp
commentCN 	=SPSC_NEXT_UF
commentEN 	=SPSC_NEXT_UF

