obj-y += hal_dbi.o common_dbi.o

obj-$(CONFIG_ARCH_SUN8IW20) += platform/dbi_sun8iw20.o
obj-$(CONFIG_ARCH_SUN8IW18) += platform/dbi_sun8iw18.o
obj-$(CONFIG_ARCH_SUN20IW2) += platform/dbi_sun20iw2.o

subdir-ccflags-y += -I drivers/hal/source/dbi
