/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef VDECODER_CONFIG_H
#define VDECODER_CONFIG_H

#define CONFIG_ENABLE_VIDEO_DECODER_MJPEG    1
#define CONFIG_ENABLE_VIDEO_DECODER_MPEG1    1
#define CONFIG_ENABLE_VIDEO_DECODER_MPEG2    1
#define CONFIG_ENABLE_VIDEO_DECODER_MPEG4    1
#define CONFIG_ENABLE_VIDEO_DECODER_MSMPEG4V1    1
#define CONFIG_ENABLE_VIDEO_DECODER_MSMPEG4V2    1
#define CONFIG_ENABLE_VIDEO_DECODER_DIVX3    1
#define CONFIG_ENABLE_VIDEO_DECODER_DIVX4    1
#define CONFIG_ENABLE_VIDEO_DECODER_DIVX5    1
#define CONFIG_ENABLE_VIDEO_DECODER_XVID    1
#define CONFIG_ENABLE_VIDEO_DECODER_H263    1
#define CONFIG_ENABLE_VIDEO_DECODER_SORENSSON_H263    1
#define CONFIG_ENABLE_VIDEO_DECODER_RXG2    1
#define CONFIG_ENABLE_VIDEO_DECODER_WMV1    1
#define CONFIG_ENABLE_VIDEO_DECODER_WMV2    1
#define CONFIG_ENABLE_VIDEO_DECODER_WMV3    1
#define CONFIG_ENABLE_VIDEO_DECODER_VP6    1
#define CONFIG_ENABLE_VIDEO_DECODER_VP8    1
#define CONFIG_ENABLE_VIDEO_DECODER_VP9    1
#define CONFIG_ENABLE_VIDEO_DECODER_RX    1
#define CONFIG_ENABLE_VIDEO_DECODER_H264    1
#define CONFIG_ENABLE_VIDEO_DECODER_AVS    1
#define CONFIG_ENABLE_VIDEO_DECODER_H265    1

#endif
