obj-$(CONFIG_SENSOR_GC2053_MIPI)      += gc2053_mipi.o
obj-$(CONFIG_SENSOR_GC4663_MIPI)      += gc4663_mipi.o
obj-$(CONFIG_SENSOR_SC2355_MIPI)      += sc2355_mipi.o
obj-$(CONFIG_SENSOR_SC5336_MIPI)      += sc5336_mipi.o
