/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef __APP_SETTINGS_I_H_
#define  __APP_SETTINGS_I_H_

#include "beetles_app.h"

#define SETTING_FOCUS_COLOR    GUI_BLACK//0xffea961d
#define SETTING_UNFOCUS_COLOR  GUI_BLACK

#define ADD_ALARM_SETTING   1
#define ENTRANCE_MENU_ID                (APP_SETTING_ID +100)
#define GENERAL_MENU_ID                 (APP_SETTING_ID +200)
#define GENERAL_FACTORY_DEFAULT_TIPS_ID (GENERAL_MENU_ID+10)    //恢复出厂设置时使用
#define GENERAL_PRODUCT_INFO_TIPS_ID    (GENERAL_MENU_ID+20)    //产品信息提示框
#define GENERAL_ADJUST_ID               (GENERAL_MENU_ID+30)
#define POWER_MANAGE_MENU_ID            (APP_SETTING_ID +300)
#define ALARM_MENU_ID                   (APP_SETTING_ID +310)
#define ALARM_SELECT_SONG_ID            (APP_SETTING_ID +320)
#define ALARM_CLOCK_ID                  (APP_SETTING_ID +330)
#define ALARM_NULL_DISK_TIPS_WIN_ID     (APP_SETTING_ID +340)   //没有磁盘提示框
#define HANDLE_MENU_ID                  (APP_SETTING_ID +400)
#define HANDLE_ADJUST_DIALOG_ID         (HANDLE_MENU_ID + 10)

#define SET_POWER_ITEM_START_X   800-490 //137
#define SET_POWER_ITEM_START_Y   0
#define SET_POWER_ITEM_H        106//106//49    
#define SET_POWER_ITEM_W        490//343


#define SET_ITEM_START_X     0//800-490 //137
#define SET_ITEM_START_Y     0
#define SET_ITEM_H          106//106//49    
#define SET_ITEM_W          300//490//343

#define ID_SWITCH_ITEM      0
#define ID_OP_UP            1
#define ID_OP_DOWN          2
#define ID_OP_ENTER         3
#define ID_OP_LEFT          4
#define ID_OP_RIGHT         5
#define ID_OP_EXIT          6
#define ID_ENTER_SMENU      7
#define ID_EXIT_SMENU       8
#define ID_SWITCH_TO_GENERAL 9
#define ID_SWITCH_TO_TIPS 10
#define ID_SWITCH_TO_ADJUST     11
#define ID_SWITCH_TO_ENTRANCE   12
#define ID_SWITCH_TO_ALARM_VIEW 13
#define ID_SWITCH_TO_ALARM_SELECT_SONG_WIN 14
#define ID_SWITCH_TO_ALARM_CLOCK_WIN        15
//////////////////////////////////////////////////////
#define ID_SWITCH_POWER_MANER       16
#define ID_SWITCH_GENERAL_SETTING       17
#define ID_SWITCH_HANDLE_ADJUST       18

#define TIPS_PRODUCT_INFO               0
#define TIPS_FACTORY_DEFAULT            1
#define APP_RESTORE_FLAG                1
typedef enum
{
    MSG_OP_UP = GUI_MSG_USER_DEF,
    MSG_OP_DOWN,
    MSG_OP_ENTER,
    MSG_OP_LEFT,
    MSG_OP_RIGHT,
    MSG_OP_EXIT,
    MSG_RESTORE_FACTORY,
    ALARM_MUSIC_PATH_MSG,
    ALARM_CLOCK_MSG
} set_msg_t;

void  main_cmd2parent(H_WIN hwin, __s32 id, unsigned long data1, unsigned long data2);

#endif
