[res_14001]
name	  	=GAME_MSGBOXBG_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./game/msgboxbg.bmp
commentCN 	=MSGBOXBG
commentEN 	=MSGBOXBG

[res_14002]
name	  	=GAME_SELECT_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./game/select.bmp
commentCN 	=SELECT
commentEN 	=SELECT

[res_14003]
name	  	=GAME_SELECT_F_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./game/select_f.bmp
commentCN 	=SELECT_F
commentEN 	=SELECT_F

