EXTRA_CFLAGS += -I./evdebug -I./input -I./keyboard -I./mouse -I./touchscreen
obj-y += sys_input.o
obj-y += input/input.o
obj-y += input/input_event.o
obj-y += keyboard/keyboarddev.o
obj-$(CONFIG_SUPPORT_MOUSE) += mouse/mousedev.o
obj-$(CONFIG_SUPPORT_TOUCHPANEL) += touchscreen/touchscreendev.o
