ccflags-y += -I$(srctree)/ekernel/components/aw/blkpart
obj-y += sdmmc_drv.o
obj-y += sdmmc_part.o
obj-$(CONFIG_SUPPORT_SDMMC_CACHE) += sdmmc_cache.o
obj-$(CONFIG_SUPPORT_SDMMC_CACHE) += cache_hash.o
