/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef __PHOTO_SSET_H__3E755E4D_EFFD_4F85_AFDC_86CE8D4989C8__
#define __PHOTO_SSET_H__3E755E4D_EFFD_4F85_AFDC_86CE8D4989C8__
//////////////////////////////////////////////////////////////////////////
#include "beetles_app.h"
#include "photo_uipara.h"
#include "app_anole.h"

#define ID_PHOTO_SCENE_SSET                2
//////////////////////////////////////////////////////////////////////////

/*notify message of sset*/
typedef enum
{
    PHOTO_SSET_NC_EXIT = 1,
    PHOTO_SSET_NC_BGMUSIC,
    PHOTO_SSET_NC_ZOOM,
    PHOTO_SSET_NC_SLIDESHOW,
    PHOTO_SSET_NC_FILEINFO,
    PHOTO_SSET_NC_AUTOPLAY,
    PHOTO_SSET_NC_INTERVAL,
    PHOTO_SSET_NC_SAVE_BG,
    PHOTO_SSET_NC_INTERVAL_USER
} __sset_nc_t;
#define PHOTO_SSET_NC_ID_UNKNOW    0xFF

extern  __sset_item_para_t  photo_sset_arry[];

__sset_create_para_t *Photo_SSET_Build_CreatePara(H_WIN  h_win);
//__s32 Photo_SSET_Destroy_CreatePara(__sset_create_para_t* create_para);
#define Photo_SSET_Destroy_CreatePara(_p) BFreeType(_p, __sset_create_para_t)

// __s32 Track_ListCreate(void);
// __s32 Subtitle_ListCreate(void);

//////////////////////////////////////////////////////////////////////////
#endif //__PHOTO_SSET_H__3E755E4D_EFFD_4F85_AFDC_86CE8D4989C8__
//End of this file
