/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef __PHOTO_MAIN_H__1BCC82B8_2AEA_420A_BB7D_BCB181413437__
#define __PHOTO_MAIN_H__1BCC82B8_2AEA_420A_BB7D_BCB181413437__
//////////////////////////////////////////////////////////////////////////
#include "App_photo_i.h" // "photo_uipara.h"
#include "photo_fileinfo.h"

#define PHOTO_MAIN_FRW_NAME               "PHOTO_MAIN_FRW"
#define PHOTO_MAIN_FRW_ID                 1000



enum
{
    PHOTO_SHOW_NULL = 0,
    PHOTO_SHOW_AUTO_PLAY,
    //  PHOTO_SHOW_MANUAL_PLAY,
    PHOTO_SHOW_PLAY_BACKWARD,
    PHOTO_SHOW_PLAY_FORWARD,
    PHOTO_SHOW_PLAY_NEXT,
    PHOTO_SHOW_PLAY_PREV,
    PHOTO_SHOW_PAUSE,
    PHOTO_SHOW_FILEINFO,
    PHOTO_SHOW_MENU,
    PHOTO_SHOW_SCALE,
};



H_WIN photo_main_frw_create(H_WIN h_parent, H_LYR layer, void *para);

#endif //__PHOTO_MAIN_H__1BCC82B8_2AEA_420A_BB7D_BCB181413437__
//End of this file
