#EXTRA_FLAGS += -I./lib_dbg_uart
subdir-ccflags-y := 	-I$(srctree)/include/melis/kernel  \
			-I$(srctree)/include/melis/kernel/drivers
obj-y += sios.o
#obj-y += uart_dbg.o
#obj-y += lib_dbg_uart/format_transformed.o
#obj-y += lib_dbg_uart/lib_dbg_uart.o
#obj-y += lib_dbg_uart/lib_uart_priv.o
#obj-y += lib_dbg_uart/lib_uart_util.o
