/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 frank@allwinnertech.com
 */

#ifndef _CCU_SUN55IW3_DSP_H_
#define _CCU_SUN55IW3_DSP_H_

#define SUNXI_DSP_CCU_BASE      0x7102000

enum {
	CLK_PLL_DSP_AUDIO1 = 0,
	CLK_PLL_DSP_AUDIO1_DIV2,
	CLK_PLL_DSP_AUDIO1_DIV5,
	CLK_PLL_DSP_AUDIO_OUT,
	CLK_DSP_DSP,
	CLK_DSP_I2S0,
	CLK_DSP_I2S1,
	CLK_DSP_I2S2,
	CLK_DSP_I2S3,
	CLK_DSP_I2S3_ASRC,
	CLK_BUS_DSP_I2S0,
	CLK_BUS_DSP_I2S1,
	CLK_BUS_DSP_I2S2,
	CLK_BUS_DSP_I2S3,
	CLK_DSP_SPDIF_TX,
	CLK_DSP_SPDIF_RX,
	CLK_BUS_DSP_SPDIF,
	CLK_DSP_DMIC,
	CLK_BUS_DSP_DMIC,
	CLK_DSP_AUDIO_CODEC_DAC,
	CLK_DSP_AUDIO_CODEC_ADC,
	CLK_BUS_DSP_AUDIO_CODEC,
	CLK_BUS_DSP_MSG,
	CLK_BUS_DSP_CFG,
	CLK_BUS_DSP_NPU_ACLK,
	CLK_BUS_DSP_NPU_HCLK,
	CLK_BUS_DSP_NPU,
	CLK_DSP_TIMER0,
	CLK_DSP_TIMER1,
	CLK_DSP_TIMER2,
	CLK_DSP_TIMER3,
	CLK_DSP_TIMER4,
	CLK_DSP_TIMER5,
	CLK_BUS_DSP_TIMER,
	CLK_BUS_DSP_DMA,
	CLK_BUS_DSP_TZMA0,
	CLK_BUS_DSP_TZMA1,
	CLK_BUS_DSP_PUBSRAM,
	CLK_BUS_DSP_MBUS,
	CLK_BUS_DSP_DMA_MBUS,
	CLK_DSP_RV,
	CLK_BUS_DSP_RV_CFG,
	CLK_BUS_DSP_RISCV_MSG,
	CLK_DSP_PWM,
	CLK_BUS_DSP_PWM,
	CLK_BUS_DSP_AHB_AUTO,

	CLK_DSP_NUMBER,
	};
#endif  /* _CCU_SUN55IW3_DSP_H_ */
