/*
*********************************************************************************************************
*                                                    eMOD
*                                   the Easy Portable/Player Operation System
*                                               mod_mmp sub-system
*
*                                   (c) Copyright 2009-2010, kevin.z.m China
*                                               All Rights Reserved
*
* File   : mediafmt.h
* Version: V1.0
* By     : kevin.z.m
* Date   : 2010-11-24 13:31
* Update : 2010-6-17 10:28, add __sw_codec_type_t by eric.w
*********************************************************************************************************
*/
#ifndef __MEDIATYPE_H_
#define __MEDIATYPE_H_

typedef enum __SW_AUDIO_FORMAT
{
    SW_AUDIO_FORMAT_UNKNOWN = 0,
    SW_AUDIO_FORMAT_AAC,
    SW_AUDIO_FORMAT_AC3,
    SW_AUDIO_FORMAT_APE,
    SW_AUDIO_FORMAT_DTS,
    SW_AUDIO_FORMAT_FLAC,
    SW_AUDIO_FORMAT_MP3,
    SW_AUDIO_FORMAT_OGG,
    SW_AUDIO_FORMAT_RA,
    SW_AUDIO_FORMAT_WAV,
    SW_AUDIO_FORMAT_WMA,
    SW_AUDIO_FORMAT_AMR,
    SW_AUDIO_FORMAT_ATRC,
    SW_AUDIO_FORMAT_MID,
    SW_AUDIO_FORMAT_DRA,
    SW_AUDIO_FORMAT_CAF,
    SW_AUDIO_FORMAT_
} __sw_audio_format_e;

typedef enum __SW_PIC_FORMAT
{
    SW_PIC_FORMAT_UNKNOWN = 0,
    SW_PIC_FORMAT_BMP,
    SW_PIC_FORMAT_GIF,
    SW_PIC_FORMAT_PNG,
    SW_PIC_FORMAT_JPG,
    SW_PIC_FORMAT_
} __sw_pic_format_e;

typedef enum __SW_FLASH_FORMAT
{
    SW_FLASH_FORMAT_UNKNOWN = 0,
    SW_FLASH_FORMAT_SWF,
    SW_FLASH_FORMAT_
} __sw_flash_format_e;

typedef enum __SW_VIDEO_FORMAT
{
    SW_VIDEO_FORMAT_UNKNOWN = 0,
    SW_VIDEO_FORMAT_AVI,
    SW_VIDEO_FORMAT_MP4,
    SW_VIDEO_FORMAT_MPG,
    SW_VIDEO_FORMAT_RM,
    SW_VIDEO_FORMAT_FLV,
    SW_VIDEO_FORMAT_PMP,
    SW_VIDEO_FORMAT_MOV,
    SW_VIDEO_FORMAT_3GP,
    SW_VIDEO_FORMAT_VOB,
    SW_VIDEO_FORMAT_DAT,
    SW_VIDEO_FORMAT_RMVB,
    SW_VIDEO_FORMAT_MKV,
    SW_VIDEO_FORMAT_WMV,
    SW_VIDEO_FORMAT_ASF,
    SW_VIDEO_FORMAT_PSR,
    SW_VIDEO_FORMAT_TP,
    SW_VIDEO_FORMAT_TS,
    SW_VIDEO_FORMAT_
} __sw_video_format_e;

typedef enum __SW_EBOOK_FORMAT
{
    SW_EBOOK_FORMAT_UNKNOWN = 0,
    SW_EBOOK_FORMAT_TXT,
    SW_EBOOK_FORMAT_C,
    SW_EBOOK_FORMAT_H,
    SW_EBOOK_FORMAT_INI,
    SW_EBOOK_FORMAT_LRC,
    SW_EBOOK_FORMAT_SRT,
    SW_EBOOK_FORMAT_PDF,

    SW_EBOOK_FORMAT_EPUB,
    SW_EBOOK_FORMAT_FB2,
    SW_EBOOK_FORMAT_PDB,
    SW_EBOOK_FORMAT_RTF,
    SW_EBOOK_FORMAT_DOC,
    SW_EBOOK_FORMAT_HTML,
    SW_EBOOK_FORMAT_MOBI,

    SW_EBOOK_FORMAT_CHM,
    SW_EBOOK_FORMAT_DJVU,
    SW_EBOOK_FORMAT_TCR,
    SW_EBOOK_FORMAT_HTM,
    SW_EBOOK_FORMAT_OEB,
    SW_EBOOK_FORMAT_IW44,
    SW_EBOOK_FORMAT_IW4,
    SW_EBOOK_FORMAT_DJV,
    SW_EBOOK_FORMAT_PRC,
    SW_EBOOK_FORMAT_OPF,
    SW_EBOOK_FORMAT_
} __sw_ebook_format_e;

typedef enum __SW_GAME_FORMAT
{
    SW_GAME_FORMAT_UNKNOWN = 0,
    SW_GAME_FORMAT_EPOS,
    SW_GAME_FORMAT_
} __sw_game_format_e;

typedef enum
{
    SW_CODEC_TYPE_NONE = 0,
    SW_CODEC_TYPE_UNKNOWN = 0xffff,         /* 无法识别             */

    SW_CODEC_TYPE_MPEG12_LAYER1 = 0x0100,   /* 音频编码类型         */
    SW_CODEC_TYPE_MPEG12_LAYER2,
    SW_CODEC_TYPE_MPEG12_LAYER3,
    SW_CODEC_TYPE_MPEG_AAC_LC,
    SW_CODEC_TYPE_AC3,
    SW_CODEC_TYPE_DTS,
    SW_CODEC_TYPE_LPCM_V,
    SW_CODEC_TYPE_LPCM_A,
    SW_CODEC_TYPE_ADPCM,
    SW_CODEC_TYPE_PCM,
    SW_CODEC_TYPE_WMA_STANDARD,
    SW_CODEC_TYPE_FLAC,
    SW_CODEC_TYPE_APE,
    SW_CODEC_TYPE_OGG,
    SW_CODEC_TYPE_RAAC,
    SW_CODEC_TYPE_COOK,
    SW_CODEC_TYPE_SIPR,
    SW_CODEC_TYPE_ATRC,
    SW_CODEC_TYPE_AMR,
    SW_CODEC_TYPE_RA,
    SW_CODEC_TYPE_MID,

    SW_CODEC_TYPE_MJPEG = 0x0200, //视频编码类型
    SW_CODEC_TYPE_MPEG1_ES,
    SW_CODEC_TYPE_MPEG2_ES,
    SW_CODEC_TYPE_XVID,
    SW_CODEC_TYPE_DIVX3,
    SW_CODEC_TYPE_DIVX4,
    SW_CODEC_TYPE_DIVX5,
    SW_CODEC_TYPE_SORENSSON_H263,
    SW_CODEC_TYPE_RMG2,
    SW_CODEC_TYPE_RMVB8,
    SW_CODEC_TYPE_RMVB9,
    SW_CODEC_TYPE_H264,
    SW_CODEC_TYPE_VC1,
    SW_CODEC_TYPE_AVS,
    SW_CODEC_TYPE_H263,
    SW_CODEC_TYPE_VP6,
    SW_CODEC_TYPE_WMV1,
    SW_CODEC_TYPE_WMV2,

    SW_CODEC_TYPE_JPEG = 0x0300, //图片编码类型
    SW_CODEC_TYPE_,
} __sw_codec_type_t;

typedef enum __SW_FILE_FORMAT
{
    SW_FILE_FORMAT_NONE         = 0,            //表示没有文件
    SW_FILE_FORMAT_UNKNOWN      = 0xFFFF,       //表示文件类型未知

    SW_FILE_AUDIO_FORMAT_AAC    = 0x1000,
    SW_FILE_AUDIO_FORMAT_AC3,
    SW_FILE_AUDIO_FORMAT_APE,
    SW_FILE_AUDIO_FORMAT_DTS,
    SW_FILE_AUDIO_FORMAT_FLAC,
    SW_FILE_AUDIO_FORMAT_MP3,
    SW_FILE_AUDIO_FORMAT_OGG,
    SW_FILE_AUDIO_FORMAT_RA,
    SW_FILE_AUDIO_FORMAT_WAV,
    SW_FILE_AUDIO_FORMAT_WMA,
    SW_FILE_AUDIO_FORMAT_AMR,
    SW_FILE_AUDIO_FORMAT_ATRC,
    SW_FILE_AUDIO_FORMAT_MID,
    SW_FILE_AUDIO_FORMAT_M4A,   //add
    SW_FILE_AUDIO_FORMAT_MP1,
    SW_FILE_AUDIO_FORMAT_MP2,
    SW_FILE_AUDIO_FORMAT_AIF,
    SW_FILE_AUDIO_FORMAT_AIFF,
    SW_FILE_AUDIO_FORMAT_AIFC,
    SW_FILE_AUDIO_FORMAT_MAC,
    SW_FILE_AUDIO_FORMAT_TTA,
    SW_FILE_AUDIO_FORMAT_CDA,
    SW_FILE_AUDIO_FORMAT_AU,
    SW_FILE_AUDIO_FORMAT_ACC,
    SW_FILE_AUDIO_FORMAT_MIDI,
    SW_FILE_AUDIO_FORMAT_RMI,
    SW_FILE_AUDIO_FORMAT_MP5,
    SW_FILE_AUDIO_FORMAT_MPA,
    SW_FILE_AUDIO_FORMAT_MPGA,
    SW_FILE_AUDIO_FORMAT_ACT,
    SW_FILE_AUDIO_FORMAT_,

    SW_FILE_VIDEO_FORMAT_AVI    = 0x2000,
    SW_FILE_VIDEO_FORMAT_MP4,
    SW_FILE_VIDEO_FORMAT_MPG,
    SW_FILE_VIDEO_FORMAT_RM,
    SW_FILE_VIDEO_FORMAT_FLV,
    SW_FILE_VIDEO_FORMAT_PMP,
    SW_FILE_VIDEO_FORMAT_MOV,
    SW_FILE_VIDEO_FORMAT_3GP,
    SW_FILE_VIDEO_FORMAT_VOB,
    SW_FILE_VIDEO_FORMAT_DAT,
    SW_FILE_VIDEO_FORMAT_RMVB,
    SW_FILE_VIDEO_FORMAT_MKV,
    SW_FILE_VIDEO_FORMAT_WMV,
    SW_FILE_VIDEO_FORMAT_ASF,
    SW_FILE_VIDEO_FORMAT_PSR,
    SW_FILE_VIDEO_FORMAT_TP,
    SW_FILE_VIDEO_FORMAT_TS,
    SW_FILE_VIDEO_FORMAT_M4V,   //add
    SW_FILE_VIDEO_FORMAT_F4V,
    SW_FILE_VIDEO_FORMAT_MPEG,
    SW_FILE_VIDEO_FORMAT_MOD,
    SW_FILE_VIDEO_FORMAT_RAM,
    SW_FILE_VIDEO_FORMAT_SCM,
    SW_FILE_VIDEO_FORMAT_OGM,
    SW_FILE_VIDEO_FORMAT_M4P,
    SW_FILE_VIDEO_FORMAT_M4B,
    SW_FILE_VIDEO_FORMAT_TPR,
    SW_FILE_VIDEO_FORMAT_PVA,
    SW_FILE_VIDEO_FORMAT_PSS,
    SW_FILE_VIDEO_FORMAT_MPE,
    SW_FILE_VIDEO_FORMAT_WV,
    SW_FILE_VIDEO_FORMAT_M2TS,
    SW_FILE_VIDEO_FORMAT_EVO,
    SW_FILE_VIDEO_FORMAT_RPM,
    SW_FILE_VIDEO_FORMAT_3GPP,
    SW_FILE_VIDEO_FORMAT_3G2,
    SW_FILE_VIDEO_FORMAT_3GP2,
    SW_FILE_VIDEO_FORMAT_QT,
    SW_FILE_VIDEO_FORMAT_WMP,
    SW_FILE_VIDEO_FORMAT_WM,
    SW_FILE_VIDEO_FORMAT_AMV,
    SW_FILE_VIDEO_FORMAT_DSM,
    SW_FILE_VIDEO_FORMAT_M1V,
    SW_FILE_VIDEO_FORMAT_M2V,
    SW_FILE_VIDEO_FORMAT_SMK,
    SW_FILE_VIDEO_FORMAT_BIK,
    SW_FILE_VIDEO_FORMAT_RAT,
    SW_FILE_VIDEO_FORMAT_VG2,
    SW_FILE_VIDEO_FORMAT_IVF,
    SW_FILE_VIDEO_FORMAT_VP6,
    SW_FILE_VIDEO_FORMAT_VP7,
    SW_FILE_VIDEO_FORMAT_D2V,
    SW_FILE_VIDEO_FORMAT_M2P,
    SW_FILE_VIDEO_FORMAT_VID,
    SW_FILE_VIDEO_FORMAT_PMP2,
    SW_FILE_VIDEO_FORMAT_MTS,
    SW_FILE_VIDEO_FORMAT_,

    SW_FILE_PIC_FORMAT_BMP      = 0x3000,
    SW_FILE_PIC_FORMAT_GIF,
    SW_FILE_PIC_FORMAT_PNG,
    SW_FILE_PIC_FORMAT_JPG,
    SW_FILE_PIC_FORMAT_,

    SW_FILE_FLASH_FORMAT_SWF    = 0x3100,
    SW_FILE_FLASH_FORMAT_,

    SW_FILE_EBOOK_FORMAT_TXT    = 0x4000,
    SW_FILE_EBOOK_FORMAT_C,
    SW_FILE_EBOOK_FORMAT_H,
    SW_FILE_EBOOK_FORMAT_INI,
    SW_FILE_EBOOK_FORMAT_LRC,
    SW_FILE_EBOOK_FORMAT_SRT,
    SW_FILE_EBOOK_FORMAT_PDF,

    SW_FILE_EBOOK_FORMAT_EPUB,
    SW_FILE_EBOOK_FORMAT_FB2,
    SW_FILE_EBOOK_FORMAT_PDB,
    SW_FILE_EBOOK_FORMAT_RTF,
    SW_FILE_EBOOK_FORMAT_DOC,
    SW_FILE_EBOOK_FORMAT_HTML,
    SW_FILE_EBOOK_FORMAT_MOBI,

    SW_FILE_EBOOK_FORMAT_CHM,
    SW_FILE_EBOOK_FORMAT_DJVU,
    SW_FILE_EBOOK_FORMAT_TCR,
    SW_FILE_EBOOK_FORMAT_HTM,
    SW_FILE_EBOOK_FORMAT_OEB,
    SW_FILE_EBOOK_FORMAT_IW44,
    SW_FILE_EBOOK_FORMAT_IW4,
    SW_FILE_EBOOK_FORMAT_DJV,
    SW_FILE_EBOOK_FORMAT_PRC,
    SW_FILE_EBOOK_FORMAT_OPF,
    SW_FILE_EBOOK_FORMAT_,

    //加密文件格式等其他格式
    SW_FILE_FORMAT_ODF          = 0x5000,   //ODF加密文件

    //用户自定义的媒体文件格式
    SW_FILE_FORMAT_PSR          = 0x6000,
    SW_FILE_FORMAT_DEV          = 0x6500,   //设备文件
    SW_FILE_FORMAT_,
} __sw_file_format_t;

#endif  /* __MEDIATYPE_H_ */
