subdir-ccflags-y += -I drivers/hal/source/usb/core
subdir-ccflags-y += -I drivers/hal/source/usb/common
subdir-ccflags-y += -I drivers/hal/source/usb/uvc/Include/
subdir-ccflags-y += -I drivers/hal/source/usb/uvc/Webcam/
subdir-ccflags-y += -I drivers/hal/source/usb/uvc/drv_webcam/
subdir-ccflags-y += -I drivers/hal/source/usb/uvc/drv_webcam/dev_cfg/
subdir-ccflags-y += -I drivers/hal/source/usb/uvc/drv_webcam/webcam_core/

obj-y += Class/
obj-y += Misc/
obj-y += Webcam/
obj-y += drv_webcam/

