ccflags-y           +=  -I$(MELIS_BASE)/${SOLUTION}/beetles/mod_desktop     \
                        -DEPDK_DEBUG_LEVEL=EPDK_DEBUG_LEVEL_LOG_ALL         \
                        -DUSED_BY_DESKTOP                                   \
                        $(SOLUTION_INCLUDE)

obj-y += dsk_wkm_spectrum.o
