[res_4001]
name	  	=MUSIC_PLAY_PAUSE_BTN_PRESSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_pause_btn_pressed.bmp
commentCN 	=PLAY_PAUSE_BTN_PRESSED
commentEN 	=PLAY_PAUSE_BTN_PRESSED

[res_4002]
name	  	=MUSIC_FORWARD_STATUS_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/forward_status.bmp
commentCN 	=FORWARD_STATUS
commentEN 	=FORWARD_STATUS

[res_4003]
name	  	=MUSIC_MENU_FCS_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/menu_fcs.bmp
commentCN 	=MENU_FCS
commentEN 	=MENU_FCS

[res_4004]
name	  	=MUSIC_BOTTOM_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/bottom.bmp
commentCN 	=BOTTOM
commentEN 	=BOTTOM

[res_4005]
name	  	=MUSIC_LIST_SCROLL_BODY_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/list_scroll_body.bmp
commentCN 	=LIST_SCROLL_BODY
commentEN 	=LIST_SCROLL_BODY

[res_4006]
name	  	=MUSIC_HEADBAR_BG_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/HEADBAR_BG.bmp
commentCN 	=HEADBAR_BG
commentEN 	=HEADBAR_BG

[res_4007]
name	  	=MUSIC_PLAY0_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play0.bmp
commentCN 	=PLAY0
commentEN 	=PLAY0

[res_4008]
name	  	=MUSIC_PROCESS_BAR_FLAG_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/process_bar_flag.bmp
commentCN 	=PROCESS_BAR_FLAG
commentEN 	=PROCESS_BAR_FLAG

[res_4009]
name	  	=MUSIC_LIST_SCROLL_TAIL_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/list_scroll_tail.bmp
commentCN 	=LIST_SCROLL_TAIL
commentEN 	=LIST_SCROLL_TAIL

[res_4010]
name	  	=MUSIC_EQ_NORMAL_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/EQ_normal.bmp
commentCN 	=EQ_NORMAL
commentEN 	=EQ_NORMAL

[res_4011]
name	  	=MUSIC_VOL_BAR_POINT_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/vol_bar_point.bmp
commentCN 	=VOL_BAR_POINT
commentEN 	=VOL_BAR_POINT

[res_4012]
name	  	=MUSIC_LIST_ITEM_UNFOCUS_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/list_item_unfocus.bmp
commentCN 	=LIST_ITEM_UNFOCUS
commentEN 	=LIST_ITEM_UNFOCUS

[res_4013]
name	  	=MUSIC_PLAY_NEXT_BTN_PRESSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_next_btn_pressed.bmp
commentCN 	=PLAY_NEXT_BTN_PRESSED
commentEN 	=PLAY_NEXT_BTN_PRESSED

[res_4014]
name	  	=MUSIC_PLAY_BACKWARD_BTN_FOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_backward_btn_focused.bmp
commentCN 	=PLAY_BACKWARD_BTN_FOCUSED
commentEN 	=PLAY_BACKWARD_BTN_FOCUSED

[res_4015]
name	  	=MUSIC_BL_90S_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/BL_90s.bmp
commentCN 	=BL_90S
commentEN 	=BL_90S

[res_4016]
name	  	=MUSIC_PLAY_BACKWARD_BTN_UNFOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_backward_btn_unfocused.bmp
commentCN 	=PLAY_BACKWARD_BTN_UNFOCUSED
commentEN 	=PLAY_BACKWARD_BTN_UNFOCUSED

[res_4017]
name	  	=MUSIC_BL_ON_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/BL_on.bmp
commentCN 	=BL_ON
commentEN 	=BL_ON

[res_4018]
name	  	=MUSIC_INFO_BAR_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/info_bar.bmp
commentCN 	=INFO_BAR
commentEN 	=INFO_BAR

[res_4019]
name	  	=MUSIC_BETTERY3_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/bettery3.bmp
commentCN 	=BETTERY3
commentEN 	=BETTERY3

[res_4020]
name	  	=MUSIC_EQ_CHANGE0_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/EQ_change0.bmp
commentCN 	=EQ_CHANGE0
commentEN 	=EQ_CHANGE0

[res_4021]
name	  	=MUSIC_PLAY_RANDOM_BTN_FOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_random_btn_focused.bmp
commentCN 	=PLAY_RANDOM_BTN_FOCUSED
commentEN 	=PLAY_RANDOM_BTN_FOCUSED

[res_4022]
name	  	=MUSIC_SD_FOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/sd_focused.bmp
commentCN 	=SD_FOCUSED
commentEN 	=SD_FOCUSED

[res_4023]
name	  	=MUSIC_EQ_JAZZ_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/EQ_jazz.bmp
commentCN 	=EQ_JAZZ
commentEN 	=EQ_JAZZ

[res_4024]
name	  	=MUSIC_PREVIOUS_STATUS_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/previous_status.bmp
commentCN 	=PREVIOUS_STATUS
commentEN 	=PREVIOUS_STATUS

[res_4025]
name	  	=MUSIC_PLAY_ALL_BTN_PRESSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_all_btn_pressed.bmp
commentCN 	=PLAY_ALL_BTN_PRESSED
commentEN 	=PLAY_ALL_BTN_PRESSED

[res_4026]
name	  	=MUSIC_PLAY_RANDOM_BTN_PRESSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_random_btn_pressed.bmp
commentCN 	=PLAY_RANDOM_BTN_PRESSED
commentEN 	=PLAY_RANDOM_BTN_PRESSED

[res_4027]
name	  	=MUSIC_EQ_CLASSIC_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/EQ_classic.bmp
commentCN 	=EQ_CLASSIC
commentEN 	=EQ_CLASSIC

[res_4028]
name	  	=MUSIC_REPEAT_ALL_BTN_FOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/repeat_all_btn_focused.bmp
commentCN 	=REPEAT_ALL_BTN_FOCUSED
commentEN 	=REPEAT_ALL_BTN_FOCUSED

[res_4029]
name	  	=MUSIC_PLAY_FORWARD_BTN_PRESSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_forward_btn_pressed.bmp
commentCN 	=PLAY_FORWARD_BTN_PRESSED
commentEN 	=PLAY_FORWARD_BTN_PRESSED

[res_4030]
name	  	=MUSIC_BL_TIME_BTN_UNFOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/BL_time_btn_unfocused.bmp
commentCN 	=BL_TIME_BTN_UNFOCUSED
commentEN 	=BL_TIME_BTN_UNFOCUSED

[res_4031]
name	  	=MUSIC_BL_10S_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/BL_10s.bmp
commentCN 	=BL_10S
commentEN 	=BL_10S

[res_4032]
name	  	=MUSIC_PLAY1_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play1.bmp
commentCN 	=PLAY1
commentEN 	=PLAY1

[res_4033]
name	  	=MUSIC_VOL_SHUT_DOWN_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/vol_shut_down.bmp
commentCN 	=VOL_SHUT_DOWN
commentEN 	=VOL_SHUT_DOWN

[res_4034]
name	  	=MUSIC_PALETTE_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/palette.bmp
commentCN 	=PALETTE
commentEN 	=PALETTE

[res_4035]
name	  	=MUSIC_VOL_SPEAKER_LEFT_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/vol_speaker_left.bmp
commentCN 	=VOL_SPEAKER_LEFT
commentEN 	=VOL_SPEAKER_LEFT

[res_4036]
name	  	=MUSIC_LIST_ITEM_FOCUS_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/list_item_focus.bmp
commentCN 	=LIST_ITEM_FOCUS
commentEN 	=LIST_ITEM_FOCUS

[res_4037]
name	  	=MUSIC_EQ_VOCAL_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/EQ_vocal.bmp
commentCN 	=EQ_VOCAL
commentEN 	=EQ_VOCAL

[res_4038]
name	  	=MUSIC_EQ_POP_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/EQ_pop.bmp
commentCN 	=EQ_POP
commentEN 	=EQ_POP

[res_4039]
name	  	=MUSIC_PLAYBAR_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/playbar.bmp
commentCN 	=PLAYBAR
commentEN 	=PLAYBAR

[res_4040]
name	  	=MUSIC_MODE_FCS_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/mode_fcs.bmp
commentCN 	=MODE_FCS
commentEN 	=MODE_FCS

[res_4041]
name	  	=MUSIC_MENU_SEL_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/menu_sel.bmp
commentCN 	=MENU_SEL
commentEN 	=MENU_SEL

[res_4042]
name	  	=MUSIC_EQ_MODE_BTN_PRESSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/EQ_mode_btn_pressed.bmp
commentCN 	=EQ_MODE_BTN_PRESSED
commentEN 	=EQ_MODE_BTN_PRESSED

[res_4043]
name	  	=MUSIC_BETTERY5_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/bettery5.bmp
commentCN 	=BETTERY5
commentEN 	=BETTERY5

[res_4044]
name	  	=MUSIC_PLAY_PRE_BTN_FOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_pre_btn_focused.bmp
commentCN 	=PLAY_PRE_BTN_FOCUSED
commentEN 	=PLAY_PRE_BTN_FOCUSED

[res_4045]
name	  	=MUSIC_ALBUM_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/album.bmp
commentCN 	=ALBUM
commentEN 	=ALBUM

[res_4046]
name	  	=MUSIC_PROCESS_BAR_TAIL_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/process_bar_tail.bmp
commentCN 	=PROCESS_BAR_TAIL
commentEN 	=PROCESS_BAR_TAIL

[res_4047]
name	  	=MUSIC_BETTERY4_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/bettery4.bmp
commentCN 	=BETTERY4
commentEN 	=BETTERY4

[res_4048]
name	  	=MUSIC_EQ_DBB_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/EQ_dbb.bmp
commentCN 	=EQ_DBB
commentEN 	=EQ_DBB

[res_4049]
name	  	=MUSIC_EQ_LYRICS0_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/EQ_lyrics0.bmp
commentCN 	=EQ_LYRICS0
commentEN 	=EQ_LYRICS0

[res_4050]
name	  	=MUSIC_FILE_SIZE_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/file_size.bmp
commentCN 	=FILE_SIZE
commentEN 	=FILE_SIZE

[res_4051]
name	  	=MUSIC_PLAYING_STATUS_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/playing_status.bmp
commentCN 	=PLAYING_STATUS
commentEN 	=PLAYING_STATUS

[res_4052]
name	  	=MUSIC_PLAY_NEXT_BTN_UNFOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_next_btn_unfocused.bmp
commentCN 	=PLAY_NEXT_BTN_UNFOCUSED
commentEN 	=PLAY_NEXT_BTN_UNFOCUSED

[res_4053]
name	  	=MUSIC_REPEAT_ONE_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/repeat_one.bmp
commentCN 	=REPEAT_ONE
commentEN 	=REPEAT_ONE

[res_4054]
name	  	=MUSIC_PLAY_FORWARD_BTN_UNFOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_forward_btn_unfocused.bmp
commentCN 	=PLAY_FORWARD_BTN_UNFOCUSED
commentEN 	=PLAY_FORWARD_BTN_UNFOCUSED

[res_4055]
name	  	=MUSIC_BETTERY0_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/bettery0.bmp
commentCN 	=BETTERY0
commentEN 	=BETTERY0

[res_4056]
name	  	=MUSIC_VOL_BAR_BG_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/vol_bar_bg.bmp
commentCN 	=VOL_BAR_BG
commentEN 	=VOL_BAR_BG

[res_4057]
name	  	=MUSIC_LIST_SCROLL_BG_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/list_scroll_bg.bmp
commentCN 	=LIST_SCROLL_BG
commentEN 	=LIST_SCROLL_BG

[res_4058]
name	  	=MUSIC_AB0_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/AB0.bmp
commentCN 	=AB0
commentEN 	=AB0

[res_4059]
name	  	=MUSIC_BL_60S_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/BL_60s.bmp
commentCN 	=BL_60S
commentEN 	=BL_60S

[res_4060]
name	  	=MUSIC_EQ_VOICE_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/EQ_voice.bmp
commentCN 	=EQ_VOICE
commentEN 	=EQ_VOICE

[res_4061]
name	  	=MUSIC_FILE_UNFOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/file_unfocused.bmp
commentCN 	=FILE_UNFOCUSED
commentEN 	=FILE_UNFOCUSED

[res_4062]
name	  	=MUSIC_PLAY_PAUSE_BTN_FOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_pause_btn_focused.bmp
commentCN 	=PLAY_PAUSE_BTN_FOCUSED
commentEN 	=PLAY_PAUSE_BTN_FOCUSED

[res_4063]
name	  	=MUSIC_PLAY_BACKWARD_BTN_PRESSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_backward_btn_pressed.bmp
commentCN 	=PLAY_BACKWARD_BTN_PRESSED
commentEN 	=PLAY_BACKWARD_BTN_PRESSED

[res_4064]
name	  	=MUSIC_EQ_MODE_BTN_UNFOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/EQ_mode_btn_unfocused.bmp
commentCN 	=EQ_MODE_BTN_UNFOCUSED
commentEN 	=EQ_MODE_BTN_UNFOCUSED

[res_4065]
name	  	=MUSIC_PAUSE0_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/pause0.bmp
commentCN 	=PAUSE0
commentEN 	=PAUSE0

[res_4066]
name	  	=MUSIC_PLAY_ONE_BTN_FOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_one_btn_focused.bmp
commentCN 	=PLAY_ONE_BTN_FOCUSED
commentEN 	=PLAY_ONE_BTN_FOCUSED

[res_4067]
name	  	=MUSIC_PARTICLE_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/particle.bmp
commentCN 	=PARTICLE
commentEN 	=PARTICLE

[res_4068]
name	  	=MUSIC_PLAY_PRE_BTN_UNFOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_pre_btn_unfocused.bmp
commentCN 	=PLAY_PRE_BTN_UNFOCUSED
commentEN 	=PLAY_PRE_BTN_UNFOCUSED

[res_4069]
name	  	=MUSIC_PLAY_PAUSE_BTN_UNFOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_pause_btn_unfocused.bmp
commentCN 	=PLAY_PAUSE_BTN_UNFOCUSED
commentEN 	=PLAY_PAUSE_BTN_UNFOCUSED

[res_4070]
name	  	=MUSIC_REPEAT_ALL_BTN_PRESSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/repeat_all_btn_pressed.bmp
commentCN 	=REPEAT_ALL_BTN_PRESSED
commentEN 	=REPEAT_ALL_BTN_PRESSED

[res_4071]
name	  	=MUSIC_BL_TIME_BTN_FOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/BL_time_btn_focused.bmp
commentCN 	=BL_TIME_BTN_FOCUSED
commentEN 	=BL_TIME_BTN_FOCUSED

[res_4072]
name	  	=MUSIC_ALBUM_NAME_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/album_name.bmp
commentCN 	=ALBUM_NAME
commentEN 	=ALBUM_NAME

[res_4073]
name	  	=MUSIC_BOUY_YELLOW_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/bouy_yellow.bmp
commentCN 	=BOUY_YELLOW
commentEN 	=BOUY_YELLOW

[res_4074]
name	  	=MUSIC_REPEAT_ONE_BTN_FOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/repeat_one_btn_focused.bmp
commentCN 	=REPEAT_ONE_BTN_FOCUSED
commentEN 	=REPEAT_ONE_BTN_FOCUSED

[res_4075]
name	  	=MUSIC_REPEAT_ONE_BTN_PRESSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/repeat_one_btn_pressed.bmp
commentCN 	=REPEAT_ONE_BTN_PRESSED
commentEN 	=REPEAT_ONE_BTN_PRESSED

[res_4076]
name	  	=MUSIC_USB_FOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/usb_focused.bmp
commentCN 	=USB_FOCUSED
commentEN 	=USB_FOCUSED

[res_4077]
name	  	=MUSIC_BL_30S_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/BL_30s.bmp
commentCN 	=BL_30S
commentEN 	=BL_30S

[res_4078]
name	  	=MUSIC_MENU_UNFOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/menu_unfocused.bmp
commentCN 	=MENU_UNFOCUSED
commentEN 	=MENU_UNFOCUSED

[res_4079]
name	  	=MUSIC_AB1_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/AB1.bmp
commentCN 	=AB1
commentEN 	=AB1

[res_4080]
name	  	=MUSIC_PROCESS_BAR_BODY_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/process_bar_body.bmp
commentCN 	=PROCESS_BAR_BODY
commentEN 	=PROCESS_BAR_BODY

[res_4081]
name	  	=MUSIC_EQ_DDB_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/EQ_ddb.bmp
commentCN 	=EQ_DDB
commentEN 	=EQ_DDB

[res_4082]
name	  	=MUSIC_BACK1_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/back1.bmp
commentCN 	=BACK1
commentEN 	=BACK1

[res_4083]
name	  	=MUSIC_FILE_FOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/file_focused.bmp
commentCN 	=FILE_FOCUSED
commentEN 	=FILE_FOCUSED

[res_4084]
name	  	=MUSIC_MENU_BG_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/menu_bg.bmp
commentCN 	=MENU_BG
commentEN 	=MENU_BG

[res_4085]
name	  	=MUSIC_BACKWARD_STATUS_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/backward_status.bmp
commentCN 	=BACKWARD_STATUS
commentEN 	=BACKWARD_STATUS

[res_4086]
name	  	=MUSIC_PROCESS_BAR_BODY0_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/process_bar_body0.bmp
commentCN 	=PROCESS_BAR_BODY0
commentEN 	=PROCESS_BAR_BODY0

[res_4087]
name	  	=MUSIC_MENU_UNFCS_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/menu_unfcs.bmp
commentCN 	=MENU_UNFCS
commentEN 	=MENU_UNFCS

[res_4088]
name	  	=MUSIC_PLAY_RANDOM_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_random.bmp
commentCN 	=PLAY_RANDOM
commentEN 	=PLAY_RANDOM

[res_4089]
name	  	=MUSIC_VOLUME_STATUS_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/volume_status.bmp
commentCN 	=VOLUME_STATUS
commentEN 	=VOLUME_STATUS

[res_4090]
name	  	=MUSIC_BOUY_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/bouy.bmp
commentCN 	=BOUY
commentEN 	=BOUY

[res_4091]
name	  	=MUSIC_EQ_SOFT_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/EQ_soft.bmp
commentCN 	=EQ_SOFT
commentEN 	=EQ_SOFT

[res_4092]
name	  	=MUSIC_BL_TIME_BTN_PRESSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/BL_time_btn_pressed.bmp
commentCN 	=BL_TIME_BTN_PRESSED
commentEN 	=BL_TIME_BTN_PRESSED

[res_4093]
name	  	=MUSIC_MENU_FOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/menu_focused.bmp
commentCN 	=MENU_FOCUSED
commentEN 	=MENU_FOCUSED

[res_4094]
name	  	=MUSIC_BETTERY1_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/bettery1.bmp
commentCN 	=BETTERY1
commentEN 	=BETTERY1

[res_4095]
name	  	=MUSIC_PLAY_ALL_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_all.bmp
commentCN 	=PLAY_ALL
commentEN 	=PLAY_ALL

[res_4096]
name	  	=MUSIC_PROCESS_BAR_POINT_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/process_bar_point.bmp
commentCN 	=PROCESS_BAR_POINT
commentEN 	=PROCESS_BAR_POINT

[res_4097]
name	  	=MUSIC_LIST_ITEM_UNFOCUS0_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/list_item_unfocus0.bmp
commentCN 	=LIST_ITEM_UNFOCUS0
commentEN 	=LIST_ITEM_UNFOCUS0

[res_4098]
name	  	=MUSIC_PLAY_NEXT_BTN_FOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_next_btn_focused.bmp
commentCN 	=PLAY_NEXT_BTN_FOCUSED
commentEN 	=PLAY_NEXT_BTN_FOCUSED

[res_4099]
name	  	=MUSIC_PLAY_ONE_BTN_PRESSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_one_btn_pressed.bmp
commentCN 	=PLAY_ONE_BTN_PRESSED
commentEN 	=PLAY_ONE_BTN_PRESSED

[res_4100]
name	  	=MUSIC_DIGIT_BG_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/digit_bg.bmp
commentCN 	=DIGIT_BG
commentEN 	=DIGIT_BG

[res_4101]
name	  	=MUSIC_SD_UNFOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/sd_unfocused.bmp
commentCN 	=SD_UNFOCUSED
commentEN 	=SD_UNFOCUSED

[res_4102]
name	  	=MUSIC_PLAY_FORWARD_BTN_FOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_forward_btn_focused.bmp
commentCN 	=PLAY_FORWARD_BTN_FOCUSED
commentEN 	=PLAY_FORWARD_BTN_FOCUSED

[res_4103]
name	  	=MUSIC_EQ_LYRICS1_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/EQ_lyrics1.bmp
commentCN 	=EQ_LYRICS1
commentEN 	=EQ_LYRICS1

[res_4104]
name	  	=MUSIC_BACK0_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/back0.bmp
commentCN 	=BACK0
commentEN 	=BACK0

[res_4105]
name	  	=MUSIC_MENU_UNSEL_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/menu_UNsel.bmp
commentCN 	=MENU_UNSEL
commentEN 	=MENU_UNSEL

[res_4106]
name	  	=MUSIC_PROCESS_BAR_HEAD_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/process_bar_head.bmp
commentCN 	=PROCESS_BAR_HEAD
commentEN 	=PROCESS_BAR_HEAD

[res_4107]
name	  	=MUSIC_EQ_DANCE_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/EQ_dance.bmp
commentCN 	=EQ_DANCE
commentEN 	=EQ_DANCE

[res_4108]
name	  	=MUSIC_PLAY_MODE1_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_mode1.bmp
commentCN 	=PLAY_MODE1
commentEN 	=PLAY_MODE1

[res_4109]
name	  	=MUSIC_VOL_BAR_BODY_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/vol_bar_body.bmp
commentCN 	=VOL_BAR_BODY
commentEN 	=VOL_BAR_BODY

[res_4110]
name	  	=MUSIC_EQ_CHANGE1_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/EQ_change1.bmp
commentCN 	=EQ_CHANGE1
commentEN 	=EQ_CHANGE1

[res_4111]
name	  	=MUSIC_LONG_STR_SCROLL_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/long_str_scroll.bmp
commentCN 	=LONG_STR_SCROLL
commentEN 	=LONG_STR_SCROLL

[res_4112]
name	  	=MUSIC_EQ_ROCK_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/EQ_rock.bmp
commentCN 	=EQ_ROCK
commentEN 	=EQ_ROCK

[res_4113]
name	  	=MUSIC_PLAY_ALL_BTN_FOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_all_btn_focused.bmp
commentCN 	=PLAY_ALL_BTN_FOCUSED
commentEN 	=PLAY_ALL_BTN_FOCUSED

[res_4114]
name	  	=MUSIC_PAUSE_STATUS_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/pause_status.bmp
commentCN 	=PAUSE_STATUS
commentEN 	=PAUSE_STATUS

[res_4115]
name	  	=MUSIC_EQ_MODE_BTN_FOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/EQ_mode_btn_focused.bmp
commentCN 	=EQ_MODE_BTN_FOCUSED
commentEN 	=EQ_MODE_BTN_FOCUSED

[res_4116]
name	  	=MUSIC_USB_UNFOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/usb_unfocused.bmp
commentCN 	=USB_UNFOCUSED
commentEN 	=USB_UNFOCUSED

[res_4117]
name	  	=MUSIC_PLAY_MODE0_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_mode0.bmp
commentCN 	=PLAY_MODE0
commentEN 	=PLAY_MODE0

[res_4118]
name	  	=MUSIC_LIST_ITEM_FOCUS0_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/list_item_focus0.bmp
commentCN 	=LIST_ITEM_FOCUS0
commentEN 	=LIST_ITEM_FOCUS0

[res_4119]
name	  	=MUSIC_BIT_RATE_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/bit_rate.bmp
commentCN 	=BIT_RATE
commentEN 	=BIT_RATE

[res_4120]
name	  	=MUSIC_BG_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/bg.bmp
commentCN 	=BG
commentEN 	=BG

[res_4121]
name	  	=MUSIC_PLAY_PRE_BTN_PRESSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_pre_btn_pressed.bmp
commentCN 	=PLAY_PRE_BTN_PRESSED
commentEN 	=PLAY_PRE_BTN_PRESSED

[res_4122]
name	  	=MUSIC_VOL_SPEAKER_RIGHT_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/vol_speaker_right.bmp
commentCN 	=VOL_SPEAKER_RIGHT
commentEN 	=VOL_SPEAKER_RIGHT

[res_4123]
name	  	=MUSIC_PLAY_ONE_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/play_one.bmp
commentCN 	=PLAY_ONE
commentEN 	=PLAY_ONE

[res_4124]
name	  	=MUSIC_LIST_SCROLL_HEAD_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/list_scroll_head.bmp
commentCN 	=LIST_SCROLL_HEAD
commentEN 	=LIST_SCROLL_HEAD

[res_4125]
name	  	=MUSIC_MODE_UNFCS_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/mode_unfcs.bmp
commentCN 	=MODE_UNFCS
commentEN 	=MODE_UNFCS

[res_4126]
name	  	=MUSIC_BETTERY2_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/bettery2.bmp
commentCN 	=BETTERY2
commentEN 	=BETTERY2

[res_4127]
name	  	=MUSIC_PERFORMER_NAME_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/performer_name.bmp
commentCN 	=PERFORMER_NAME
commentEN 	=PERFORMER_NAME

[res_4128]
name	  	=MUSIC_NEXT_STATUS_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/next_status.bmp
commentCN 	=NEXT_STATUS
commentEN 	=NEXT_STATUS

[res_4129]
name	  	=MUSIC_PAUSE1_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/pause1.bmp
commentCN 	=PAUSE1
commentEN 	=PAUSE1

[res_4130]
name	  	=MUSIC_REPEAT_ALL_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/repeat_all.bmp
commentCN 	=REPEAT_ALL
commentEN 	=REPEAT_ALL

[res_4131]
name	  	=MUSIC_PALY_PAUSE_BTN_UNFOCUSED_BMP
file	  	=/source/livedesk/beetles/sun20iw1_app/res/theme/./music/paly_pause_btn_unfocused.bmp
commentCN 	=PALY_PAUSE_BTN_UNFOCUSED
commentEN 	=PALY_PAUSE_BTN_UNFOCUSED

