/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef  __REG_DISPLAY_H__
#define  __REG_DISPLAY_H__
#include <kconfig.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum tag_LION_DISP_TVFORMAT
{
    LION_DISP_TV_PAL,
    LION_DISP_TV_NTSC,
    LION_DISP_TV_PAL_SVIDEO,
    LION_DISP_TV_NTSC_SVIDEO,
    LION_DISP_TV_PAL_CVBS_SVIDEO,
    LION_DISP_TV_NTSC_CVBS_SVIDEO,

    LION_DISP_TV_480I,
    LION_DISP_TV_576I,
    LION_DISP_TV_480P,
    LION_DISP_TV_576P,
    LION_DISP_TV_720P_50HZ,
    LION_DISP_TV_720P_60HZ,
    LION_DISP_TV_1080I_50HZ,
    LION_DISP_TV_1080I_60HZ,
    LION_DISP_TV_1080P_24HZ,
    LION_DISP_TV_1080P_50HZ,
    LION_DISP_TV_1080P_60HZ,

    LION_DISP_HDMI_480I,
    LION_DISP_HDMI_576I,
    LION_DISP_HDMI_480P,
    LION_DISP_HDMI_576P,
    LION_DISP_HDMI_720P_50HZ,
    LION_DISP_HDMI_720P_60HZ,
    LION_DISP_HDMI_1080I_50HZ,
    LION_DISP_HDMI_1080I_60HZ,
    LION_DISP_HDMI_1080P_24HZ,
    LION_DISP_HDMI_1080P_50HZ,
    LION_DISP_HDMI_1080P_60HZ,

    LION_DISP_VGA_H1680_V1050,
    LION_DISP_VGA_H1440_V900,
    LION_DISP_VGA_H1360_V768,
    LION_DISP_VGA_H1280_V1024,
    LION_DISP_VGA_H1024_V768,
    LION_DISP_VGA_H800_V600,
    LION_DISP_VGA_H640_V480,
    LION_DISP_VGA_H1440_V900_RB,
    LION_DISP_VGA_H1680_V1050_RB,
    LION_DISP_VGA_H1920_V1080_RB,
    LION_DISP_VGA_H1920_V1080,

    LION_DISP_LCD,
    LION_DISP_LCD_TV_NTSC,
    LION_DISP_LCD_TV_PAL,
    LION_DISP_UNKNOWN = -1

}
__lion_disp_format_e;

#ifdef __cplusplus
}
#endif

#endif     //  ifndef __REG_DISPLAY_H__

/* end of reg_display.h */
