ccflags-y += \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/libisp

subdir-ccflags-y += \
    -I$(srctree)/ekernel/components/avframework/v4l2/include \
    -I$(srctree)/ekernel/components/avframework/v4l2/include/uapi \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/system/public/include \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/system/public/include/vo \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/system/public/include/utils \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/system/public/libion/include \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/include \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/include/utils \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/include/media \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/include/media/utils \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/config \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/include \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/include/utils \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/include/include_render \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/include/component \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/include/audio \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/include/videoIn \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/include_demux \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/include_stream \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/include_FsWriter \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/include_muxer \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/textEncLib/include \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/libcedarx \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/libcedarx/libcore/base/include \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/libcedarx/libcore/common/plugin \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/libcedarx/libcore/common/iniparser \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/libcedarx/libcore/parser/include \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/libcedarx/libcore/stream/include \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/libmuxer/mp4_muxer \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/libcedarc \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/libcedarc/include \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/AudioLib/osal \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/AudioLib/midware/encoding \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/AudioLib/midware/encoding/include \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/AudioLib/midware/decoding/include \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/libISE/include \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/libisp/include \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/libisp/include/device \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/libisp/include/V4l2Camera \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/libisp/isp_tuning \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/sample/configfileparser \
    -I$(srctree)/ekernel/components/net/rt-thread/lwip/src/include/compat/posix \
    -I$(srctree)/ekernel/components/net/rt-thread/lwip/src/include \
    -I$(srctree)/ekernel/components/net/rt-thread/lwip/src/arch/include \
    -I$(srctree)/ekernel/components/net/rt-thread/lwip/src \
    -I$(srctree)/ekernel/components/aw/multi_console \
    -I$(srctree)/ekernel/drivers/include/hal \
    -I$(srctree)/ekernel/drivers \
    -I$(srctree)/include/media

ifeq ($(CONFIG_mpp_aec), y)
subdir-ccflags-y += \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/aec_lib/include
endif

ifeq ($(CONFIG_mpp_softdrc), y)
subdir-ccflags-y += \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/drc_lib/include
endif

ifeq ($(CONFIG_mpp_ai_agc), y)
subdir-ccflags-y += \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/agc_lib/include
endif

ifeq ($(CONFIG_mpp_ans_libwebrtc), y)
subdir-ccflags-y += \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/ans_lib/libwebrtc
endif

ifeq ($(CONFIG_mpp_ans_liblstm), y)
subdir-ccflags-y += \
    -I$(srctree)/ekernel/components/avframework/eyesee-mpp/middleware/sun8iw19p1/media/LIBRARY/ans_lib/liblstm
endif

CFLAGS_REMOVE_CedarXMetaData.o += -Werror=implicit-int \
				-Werror=strict-prototypes \
				-Wno-declaration-after-statement \
				-Wno-old-style-declaration \
				-Wno-strict-prototypes \
				-Wno-discarded-qualifiers
CFLAGS_REMOVE_video_render_linux.o += -Werror=implicit-int \
				-Werror=strict-prototypes \
				-Wno-declaration-after-statement \
				-Wno-old-style-declaration \
				-Wno-strict-prototypes \
				-Wno-discarded-qualifiers
CFLAGS_REMOVE_CedarXNativeRenderer.o += -Werror=implicit-int \
				-Werror=strict-prototypes \
				-Wno-declaration-after-statement \
				-Wno-old-style-declaration \
				-Wno-strict-prototypes \
				-Wno-discarded-qualifiers

obj-y += \
    media/utils/BITMAP_S.o \
    media/utils/CedarXMetaData.o \
    media/utils/cedarx_avs_counter.o \
    media/utils/SystemBase.o \
    media/utils/tmessage.o \
    media/utils/tsemaphore.o \
    media/utils/PIXEL_FORMAT_E_g2d_format_convert.o \
    media/utils/EPIXELFORMAT_g2d_format_convert.o \
    media/utils/VIDEO_FRAME_INFO_S.o \
    media/utils/dup2SeldomUsedFd.o \
    media/utils/media_common.o \
    media/utils/mpi_videoformat_conversion.o \
    media/utils/mm_comm_venc.o \
    media/utils/video_buffer_manager.o \
    media/LIBRARY/libstream/cedarx_outstream.o \
    media/LIBRARY/libstream/cedarx_outstream_external.o \
    media/LIBRARY/libstream/cedarx_stream.o \
    media/LIBRARY/libstream/cedarx_stream_file.o \
    media/component/ComponentsRegistryTable.o \
    media/component/mm_component.o \
    media/mpi_sys.o \
    media/mpi_clock.o \
    media/mpi_region.o \
    media/ChannelRegionInfo.o \
    media/component/mm_component.o \
    media/component/ComponentsRegistryTable.o \
    media/component/Clock_Component.o \
    media/component/RecAVSync.o \
    sample/configfileparser/confparser.o
obj-$(CONFIG_mpp_muxer) += \
    media/mpi_mux.o \
    media/component/RecRenderSink.o \
    media/component/RecRender_cache.o \
    media/component/RecRender_Component.o \
    media/LIBRARY/libFsWriter/FsWriter.o \
    media/LIBRARY/libFsWriter/FsWriteDirect.o \
    media/LIBRARY/libFsWriter/FsSimpleCache.o \
    media/LIBRARY/libFsWriter/FsCache.o \
    media/LIBRARY/libmuxer/
obj-$(CONFIG_mpp_vi) += \
    media/LIBRARY/libisp/ \
    media/mpi_vi.o \
    media/mpi_isp.o \
    media/component/VideoVirVi_Component.o \
    media/videoIn/videoInputHw.o \
    media/videoIn/VIPPDrawOSD_V5.o
obj-$(CONFIG_mpp_ise) += \
    media/mpi_ise.o \
    media/component/VideoISE_Component.o
obj-$(CONFIG_mpp_venc) += \
    media/mpi_venc.o \
    media/component/VideoEnc_Component.o
obj-$(CONFIG_mpp_vdec) += \
    media/mpi_vdec.o \
    media/component/VideoDec_Component.o \
    media/component/VideoDec_InputThread.o
obj-y += media/LIBRARY/libcedarc/
obj-y += media/LIBRARY/libcedarx/
obj-$(CONFIG_mpp_demuxer) += \
    media/LIBRARY/libdemux/ \
    media/mpi_demux.o \
    media/component/Demux_Component.o
obj-$(CONFIG_mpp_aenc) += \
    media/mpi_aenc.o \
    media/component/AudioEnc_Component.o \
    media/LIBRARY/AudioLib/midware/encoding/aencoder.o \
    media/LIBRARY/AudioLib/midware/encoding/pcm_enc.o \
    media/LIBRARY/AudioLib/midware/encoding/g711/g711.o \
    media/LIBRARY/AudioLib/midware/encoding/g711/g711a_enc.o \
    media/LIBRARY/AudioLib/midware/encoding/g711/g711codec.o \
    media/LIBRARY/AudioLib/midware/encoding/g711/g711u_enc.o \
    media/LIBRARY/AudioLib/midware/encoding/g726/g726.o \
    media/LIBRARY/AudioLib/midware/encoding/g726/g726_enc.o
obj-$(CONFIG_mpp_adec) += \
    media/mpi_adec.o \
    media/component/AudioDec_Component.o \
    media/LIBRARY/AudioLib/midware/decoding/adecoder.o \
    media/LIBRARY/AudioLib/midware/decoding/src/AudioDec_Decode.o \
    media/LIBRARY/AudioLib/midware/decoding/src/cedar_abs_packet_hdr.o \
    media/LIBRARY/AudioLib/midware/decoding/src/g711_dec/g711a/g711a_lib_layer.o \
    media/LIBRARY/AudioLib/midware/decoding/src/g711_dec/g711a/g711a_decInternal.o \
    media/LIBRARY/AudioLib/midware/decoding/src/g711_dec/g711a/g711a_decInternal.o \
    media/LIBRARY/AudioLib/midware/decoding/src/g711_dec/g711a/g711codec.o \
    media/LIBRARY/AudioLib/midware/decoding/src/g711_dec/g711a/g711.o \
    media/LIBRARY/AudioLib/midware/decoding/src/g711_dec/g711u/g711u_lib_layer.o \
    media/LIBRARY/AudioLib/midware/decoding/src/g711_dec/g711u/g711u_decInternal.o \
    media/LIBRARY/AudioLib/midware/decoding/src/g711_dec/g711u/g711u_decInternal.o \
    media/LIBRARY/AudioLib/midware/decoding/src/g711_dec/g711u/g711codec.o \
    media/LIBRARY/AudioLib/midware/decoding/src/g711_dec/g711u/g711.o
    #media/LIBRARY/AudioLib/midware/decoding/src/g726_dec/g726_decInternal.o \
    #media/LIBRARY/AudioLib/midware/decoding/src/g726_dec/g726.o \
    #media/LIBRARY/AudioLib/midware/decoding/src/g726_dec/g726_lib_layer.o
obj-$(CONFIG_mpp_textenc) += \
    media/mpi_tenc.o \
    media/component/TextEnc_Component.o \
    media/LIBRARY/textEncLib/TextEncApi.o
obj-$(CONFIG_mpp_aec) +=
obj-$(CONFIG_mpp_ans) +=
obj-$(CONFIG_mpp_eis) +=
obj-$(CONFIG_mpp_vo) += \
    media/librender/video_render.o \
    media/librender/video_render_linux.o \
    media/librender/CedarXNativeRenderer.o \
    media/mpi_vo.o \
    media/component/VideoRender_Component.o
obj-$(CONFIG_mpp_uvc) +=
obj-$(CONFIG_mpp_aio) += \
    media/mpi_ai.o \
    media/mpi_ao.o \
    media/component/AIChannel_Component.o \
    media/component/AOChannel_Component.o \
    media/audio/alsa_interface.o \
    media/audio/audio_hw.o \
    media/audio/pcmBufferManager.o

obj-$(CONFIG_isp_tool_vencoder)  += \
	media/LIBRARY/libisp/tuning_app/isp_vencode/ispSimpleCode.o

ifeq ($(CONFIG_isp_tool_vencoder), y)
subdir-ccflags-y += \
	-DISPTOOL_VENCODE
endif

obj-$(CONFIG_isp_tool) += \
    media/LIBRARY/libisp/tuning_app/awTuningApp.o \
    media/LIBRARY/libisp/tuning_app/log_handle.o \
    media/LIBRARY/libisp/tuning_app/socket_protocol.o \
    media/LIBRARY/libisp/tuning_app/thread_pool.o \
    media/LIBRARY/libisp/tuning_app/server/capture_image.o \
    media/LIBRARY/libisp/tuning_app/server/isp_handle.o \
    media/LIBRARY/libisp/tuning_app/server/isptool_terminal.o \
    media/LIBRARY/libisp/tuning_app/server/server.o \
    media/LIBRARY/libisp/tuning_app/server/server_api.o \
    media/LIBRARY/libisp/tuning_app/server/server_core.o \
    media/LIBRARY/libisp/tuning_app/server/register_opt.o \
    media/LIBRARY/libisp/tuning_app/server/raw_flow_opt.o \

#obj-$(CONFIG_mpp_aec) += sample/sample_aec/sample_aec.o
#obj-y += sample/sample_ai/sample_ai.o
#obj-y += sample/sample_ai2aenc2muxer/sample_ai2aenc2muxer.o
#obj-y += sample/sample_ao/sample_ao.o
#obj-y += sample/sample_aoSync/sample_aoSync.o
#obj-y += sample/sample_demux2adec2ao/sample_demux2adec2ao.o
#obj-y += sample/sample_demux2vdec2vo/sample_demux2vdec2vo.o
#obj-y += sample/sample_multi_vi2venc2muxer/sample_multi_vi2venc2muxer.o
#obj-y += sample/sample_region/sample_region.o
obj-y += sample/sample_virvi/sample_virvi.o
#obj-y += sample/sample_virvi2fish2venc/sample_virvi2fish2venc.o
#obj-y += sample/sample_virvi2fish2vo/sample_virvi2fish2vo.o
#obj-y += sample/sample_virvi2vo/sample_virvi2vo.o
#obj-y += sample/sample_virvi2vo_zoom/sample_virvi2vo_zoom.o
#obj-y += sample/sample_virtual2vo/sample_virtual2vo.o
#obj-y += sample/sample_virvi2venc2muxer/sample_vi2venc2muxer.o
obj-y += sample/sample_virvi2venc/sample_virvi2venc.o
#obj-y += sample/sample_thumb/sample_thumbnail.o
#obj-y += sample/sample_vi_g2d/sample_vi_g2d.o
#obj-y += sample/sample_aenc/sample_aenc.o
#obj-y += sample/sample_adec/sample_adec.o
#obj-y += sample/sample_udp/sample_udp.o
