/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef __LYRWIN_E_H__
#define __LYRWIN_E_H__
#include <kconfig.h>

extern __s32  GUI_LyrWinSetSrcWindow(H_WIN lyrwin, const RECT *rect);
extern __s32  GUI_LyrWinSetScnWindow(H_WIN lyrwin, const RECT *rect);
extern __s32  GUI_LyrWinGetSrcWindow(H_WIN lyrwin, RECT *rect);
extern __s32  GUI_LyrWinGetScnWindow(H_WIN lyrwin, RECT *rect);
extern __s32  GUI_LyrWinGetFB(H_WIN lyrwin, FB *fb);
extern __s32  GUI_LyrWinSetFB(H_WIN lyrwin, const FB *fb);
extern __s32  GUI_LyrWinSetBackFB(__gui_back_src_t mode, void *src);
extern __s32  GUI_LyrWinSetSta(H_WIN lyrwin, __gui_lyrwin_sta_t status);
extern __s32  GUI_LyrWinSel(H_WIN lyrwin);
extern __s32  GUI_LyrWinCacheOn(void);
extern __s32  GUI_LyrWinCacheOff(void);
extern __s32  GUI_LyrWinFlushFB(H_WIN lyrwin);
extern __s32  GUI_LyrWinSetAlpha(H_WIN lyrwin, __u8 alpha);
extern __s32  GUI_LyrWinAlphaOn(H_WIN lyrwin);
extern __s32  GUI_LyrWinAlphaOff(H_WIN lyrwin);
extern __s32  GUI_LyrWinCKOn(H_WIN lyrwin);
extern __s32  GUI_LyrWinCKOff(H_WIN lyrwin);
extern __s32  GUI_LyrWinSetBottom(H_WIN lyrwin);
extern __s32  GUI_LyrWinSetTop(H_WIN lyrwin);

extern H_LYR GUI_LyrWinGetHWLyr(H_LYR h_lyr);

#endif
