ccflags-y           +=  -I$(MELIS_BASE)/${SOLUTION}/beetles/mod_desktop     \
                        -DEPDK_DEBUG_LEVEL=EPDK_DEBUG_LEVEL_LOG_ALL         \
                        -DUSED_BY_DESKTOP                                   \
                        $(SOLUTION_INCLUDE)

obj-y += dsk_wkm_ab_i.o
obj-y += dsk_wkm_eq_i.o
obj-y += dsk_wkm_feedbackq.o
obj-y += dsk_wkm_ff_rr_speed_i.o
obj-y += dsk_wkm_fsm_ctrl_i.o
obj-y += dsk_wkm_lyric_i.o
obj-y += dsk_wkm_media_info_i.o
obj-y += dsk_wkm_npl_i.o
obj-y += dsk_wkm_play_mode_i.o
obj-y += dsk_wkm_play_speed_i.o
obj-y += dsk_wkm_spectrum_i.o
obj-y += dsk_wkm_star_i.o
obj-y += dsk_wkm_syn_op.o